Repository hedgedoc/hedgedoc, pull requests merged in 2019-04, with the labels that each got.

#22 Add new screenshot
  public/screenshot.png
Labels: enhancement

#35 specifying the locale jsons to be in the exact style of poeditor
  .editorconfig
  app.js
Labels: enhancement

#37 change default mode to "both" when clicking edit
  lib/response.js
Labels: enhancement

#31 Hide port minio
  lib/web/imageRouter/minio.js
Labels: enhancement

#30 Added a configuration option for passport-saml:
  config.json.example
  docs/configuration-env-vars.md
  lib/config/default.js
  lib/config/environment.js
  lib/config/hackmdEnvironment.js
  lib/web/auth/saml/index.js
Labels: enhancement

#41 Fix broken dependency js-sequence-diagrams
  package.json
Labels: bug

#33 Add support for image hosting with lutim
  docs/configuration-config-file.md
  docs/configuration-env-vars.md
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/web/imageRouter/lutim.js
  package.json
Labels: feature request

#42 Update meta-marked to fix possible vulnerabilities
  .travis.yml
  package.json
Labels: bug

#43 Add community forum to help section
  locales/en.json
  public/views/shared/help-modal.ejs
Labels: enhancement

#48 Fix stored XSS in the graphviz error message rendering
  package.json
  public/js/extra.js
Labels: bug

#50 fix unix socket not removed on shutdown
  app.js
Labels: bug

#51 Replace js-url with wurl
  package.json
  public/js/history.js
  public/js/index.js
  public/views/index/foot.ejs
  webpack.common.js
Labels: enhancement
