Repository hedgedoc/hedgedoc, pull requests merged in 2019-09, with the labels that each got.

#165 Add documentation for the new imprint feature
  docs/guides/providing-terms.md
Labels: enhancement

#32 make aws s3 endpoint configurable
  lib/config/environment.js
  lib/web/imageRouter/s3.js
Labels: enhancement

#171 Move sequelize-cli from devDependencies to dependencies, because it is needed to run migrations at run-time
  package.json
Labels: bug

#173 Extended config.js documentation on login methods and libravatar
  docs/configuration-config-file.md
  docs/configuration-env-vars.md
Labels: enhancement

#180 Fixed #179 (redirect loop with a trailing slash)
  app.js
  lib/config/default.js
Labels: bug

#170 Added endpoint for note-creation with given alias
  lib/response.js
  lib/web/noteRouter.js
Labels: feature request
