Repository hedgedoc/hedgedoc, pull requests merged in 2019-10, with the labels that each got.

#187 remove legacy code to solve #58
  lib/realtime.js
Labels: Hacktoberfest, enhancement

#189 Added Czech translation
  app.js
  locales/cs.json
  public/views/index/body.ejs
Labels: Hacktoberfest, enhancement

#192 Slovak locale
  app.js
  locales/sk.json
  public/views/index/body.ejs
Labels: Hacktoberfest, enhancement

#191 Add customizable opengraph metadata for notes (see #40)
  lib/models/note.js
  lib/response.js
  public/docs/yaml-metadata.md
  public/views/codimd/head.ejs
  public/views/index/head.ejs
  public/views/pretty.ejs
Labels: Hacktoberfest, feature request

#199 Fix broken error template due to missing opengraph
  lib/response.js
Labels: Hacktoberfest, bug

#200 Add API documentation (#172)
  docs/dev/api.md
  docs/dev/openapi.yml
Labels: Hacktoberfest, enhancement

#206 Don't accept sandbox attribute
  public/js/render.js
Labels: Hacktoberfest, bug

#205 Allow to generate lower case header references through the config
  config.json.example
  lib/config/default.js
  lib/web/statusRouter.js
  public/js/extra.js
  public/js/lib/common/constant.ejs
Labels: Hacktoberfest, enhancement

#208 Replace `npm` with `yarn` commands in docs.
  docs/dev/getting-started.md
  docs/setup/manual-setup.md
Labels: Hacktoberfest, enhancement

#215 Upgrade all ORM/database related packages
  package.json
  yarn.lock
Labels: enhancement

#212 Remove unused webpack plugins from package.json
  package.json
Labels: Hacktoberfest, enhancement

#209 Improve webpack dev documentation
  docs/dev/webpack.md
Labels: Hacktoberfest, enhancement

#210 Fix compatibility with MathJax 2.7.6
  package.json
  webpack.common.js
Labels: Hacktoberfest, bug

#217 Fix crash in lutim integration
  lib/web/imageRouter/lutim.js
Labels: Hacktoberfest, bug
