Repository hedgedoc/hedgedoc, pull requests merged in 2020-06, with the labels that each got.

#390 Ensure session cookies are secure
  app.js
Labels: bug

#404 improve documentation about configuration
  README.md
  docs/configuration-config-file.md
  docs/configuration-env-vars.md
  docs/configuration.md
Labels: documentation

#413 Fully dedicate our soul to yarn
  package.json
Labels: enhancement

#424 Fix browser logo links
  README.md
Labels: bug

#423 Fix browser logo links
  README.md
Labels: bug

#421 Centralize permission checking
  src/lib/realtime.ts
  src/lib/web/note/util.ts
Labels: enhancement
