Repository hedgedoc/hedgedoc, pull requests merged in 2020-07, with the labels that each got.

#432 Fix yaml-metadata docs example for lang
  public/docs/yaml-metadata.md
Labels: documentation

#410 doc: add a markdown linting configuration file
  .remarkrc
  .travis.yml
  CHANGELOG.md
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/configuration.md
  docs/dev/api.md
  docs/dev/getting-started.md
  docs/dev/ot.md
  docs/dev/webpack.md
  docs/guides/auth/github.md
  docs/guides/auth/gitlab-self-hosted.md
  docs/guides/auth/keycloak.md
  docs/guides/auth/ldap-ad.md
  docs/guides/auth/mattermost-self-hosted.md
  docs/guides/auth/nextcloud.md
  docs/guides/auth/oauth.md
  docs/guides/auth/saml-onelogin.md
  docs/guides/auth/saml.md
  docs/guides/auth/twitter.md
  docs/guides/migrate-etherpad.md
  docs/guides/migrations-and-breaking-changes.md
  docs/guides/minio-image-upload.md
  docs/guides/providing-terms.md
  docs/guides/s3-image-upload.md
  docs/history.md
  docs/setup/cloudron.md
  docs/setup/docker-linuxserver.md
  docs/setup/docker.md
  docs/setup/heroku.md
  docs/setup/kubernetes.md
  docs/setup/manual-setup.md
  docs/slide-options.md
  docs/url-scheme.md
  package.json
  public/docs/features.md
  public/docs/privacy.md.example
  public/docs/release-notes.md
  public/docs/slide-example.md
  public/docs/yaml-metadata.md
  yarn.lock
Labels: enhancement

#384 Run database migrations automatically on startup
  package.json
  src/lib/app.ts
  src/lib/migrations/20150504155329-create-users.js
  src/lib/migrations/20150508114741-create-notes.js
  src/lib/migrations/20150515125813-create-temp.js
  src/lib/migrations/20150702001020-update-to-0_3_1.js
  src/lib/migrations/20150915153700-change-notes-title-to-text.js
  src/lib/migrations/20160112220142-note-add-lastchange.js
  src/lib/migrations/20160420180355-note-add-alias.js
  src/lib/migrations/20160515114000-user-add-tokens.js
  src/lib/migrations/20160607060246-support-revision.js
  src/lib/migrations/20160703062241-support-authorship.js
  src/lib/migrations/20161009040430-support-delete-note.js
  src/lib/migrations/20161201050312-support-email-signin.js
  src/lib/migrations/20180306150303-fix-enum.js
  src/lib/migrations/20180326103000-use-text-in-tokens.js
  src/lib/migrations/20180525153000-user-add-delete-token.js
  src/lib/models/index.ts
  yarn.lock
Labels: enhancement

#350 allow to set a saml client certificate
  docs/configuration.md
  docs/guides/auth/keycloak.md
  docs/guides/auth/saml-keycloak.md
  docs/images/auth/keycloak_add_client.png
  docs/images/auth/keycloak_client_overview.png
  docs/images/auth/keycloak_clients_overview.png
  docs/images/auth/keycloak_force_idformat.png
  docs/images/auth/keycloak_idp_cert.png
  docs/images/auth/keycloak_mapper_email.png
  docs/images/auth/keycloak_mapper_overview.png
  docs/images/auth/keycloak_mapper_username.png
  docs/images/auth/keycloak_saml_export_cert.png
  docs/images/auth/keycloak_saml_export_cert_details.png
  docs/images/auth/keycloak_saml_import_cert.png
  docs/images/auth/keycloak_saml_import_cert_details.png
  lib/config/default.js
  lib/config/environment.js
  lib/web/auth/saml/index.js
Labels: feature request

#236 Adjust features.md slightly after #232
  public/docs/features.md
Labels: documentation

#461 Add note about renaming
  README.md
Labels: documentation
