Repository hedgedoc/hedgedoc, pull requests merged in 2020-05, with the labels that each got.

#335 Add document explaining different URLs
  docs/url-scheme.md
Labels: documentation

#356 setHistory: Do not parse history into an array again
  lib/history.ts
Labels: enhancement

#342 Fix redirected, outdated links and convert all to https
  public/docs/features.md
Labels: enhancement

#344 Fix redirected, outdated links and convert all to https
  public/docs/features.md
Labels: enhancement

#361 Tests and Fixes for Auth Middlewares
  lib/letter-avatars.ts
  lib/models/user.ts
  lib/web/auth/dropbox/index.ts
  test/auth.ts
Labels: bug, enhancement
