Repository hedgedoc/hedgedoc, pull requests merged in 2020-11, with the labels that each got.

#548 Use URL constructor instead of regex to check for valid URL
  public/js/extra.js
Labels: bug

#564 Fix CodeMirror after #551 broke it
  webpack.common.js
  yarn.lock
Labels: bug

#566 Save note title to database when creating a note
  lib/web/note/util.js
Labels: enhancement

#565 Fix deprecation warning of "includeSubDomains"
  app.js
Labels: bug

#572 Fix image width on mobile view for front page
  public/css/cover.css
Labels: bug

#574 Updated screenshot
  docs/images/HedgeDoc-1.7.0-features.png
  public/screenshot.png
Labels: documentation, enhancement, frontend

#5 Add some version checks to setup script
  bin/setup
Labels: enhancement

#591 Remove irritating footer files
  public/views/error.ejs
  public/views/hedgedoc.ejs
  public/views/hedgedoc/footer.ejs
  public/views/index.ejs
  public/views/index/foot.ejs
  public/views/index/footer.ejs
Labels: bug

#595 Add oauth2 authorization
  docs/configuration.md
  lib/config/environment.js
  lib/web/auth/oauth2/index.js
Labels: enhancement

#602 Remove reference to nonexisting DOM element
  public/js/index.js
Labels: bug

#603 Replace references to Matrix room with chat.hedgedoc.org
  README.md
  SECURITY.md
  public/docs/features.md
  public/views/index/body.ejs
Labels: documentation, enhancement

#599 Fix shortcut icon urls pointing to old (nonexistent) files
  public/views/hedgedoc/head.ejs
  public/views/html.hbs
  public/views/index/head.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
Labels: bug, frontend

#601 chore: bump AWS SDK from 2.345.0 to 2.521.0
  package.json
  yarn.lock
Labels: dependencies

#571 Generate new AUTHORS file
  .mailmap
  AUTHORS
Labels: documentation

#597 Update manual install docs & config errors
  docs/setup/manual-setup.md
  lib/config/index.js
Labels: documentation

#611 Change label used by renovate to "type: maintenance"
  renovate.json
Labels: priority: medium, type: enhancement
