Repository hedgedoc/hedgedoc, pull requests merged in 2020-12, with the labels that each got.

#605 Update yunohost.md
  docs/setup/yunohost.md
Labels: type: documentation

#614 Update issue templates to use the new labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question---other.md
Labels: type: maintenance

#610 [Migrations] Add variant of error message to catch block
  lib/migrations/20150702001020-update-to-0_3_1.js
  lib/migrations/20160112220142-note-add-lastchange.js
  lib/migrations/20160420180355-note-add-alias.js
  lib/migrations/20160515114000-user-add-tokens.js
  lib/migrations/20160607060246-support-revision.js
  lib/migrations/20160703062241-support-authorship.js
  lib/migrations/20161009040430-support-delete-note.js
  lib/migrations/20161201050312-support-email-signin.js
  lib/migrations/20180525153000-user-add-delete-token.js
  lib/migrations/20200321153000-fix-account-deletion.js
Labels: priority: critical, type: bug

#609 Fix crash when OAuth2 config parameters are missing
  lib/web/auth/oauth2/index.js
Labels: priority: critical, type: bug

#613 Fix some typos in history.md
  docs/history.md
Labels: type: documentation

#625 Document reverse proxy config for Apache
  docs/setup/reverse-proxy.md
Labels: type: documentation

#632 Generate CSS filenames with contenthash
  webpack.common.js
Labels: type: enhancement
