Repository hedgedoc/hedgedoc, pull requests merged in 2020-10, with the labels that each got.

#502 Use custom logger
  src/api/public/me/me.controller.spec.ts
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.spec.ts
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.spec.ts
  src/api/public/notes/notes.controller.ts
  src/api/public/public-api.module.ts
  src/app.module.ts
  src/history/history.module.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/logger/console-logger.service.ts
  src/logger/logger.module.ts
  src/logger/nest-console-logger.service.ts
  src/main.ts
  src/monitoring/monitoring.module.ts
  src/notes/notes.module.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/permissions/permissions.module.ts
  src/revisions/revisions.module.ts
  src/revisions/revisions.service.spec.ts
  src/revisions/revisions.service.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/public-api/notes.e2e-spec.ts
Labels: enhancement

#513 Fix stack trace logging
  src/logger/nest-console-logger.service.ts
Labels: bug

#515 Collect coverage information for E2E tests
  jest-e2e.json
  package.json
  test/jest-e2e.json
Labels: enhancement

#517 Add revisions documentation - Issue #196
  public/docs/features.md
Labels: documentation

#543 Tests for MediaController
  package.json
  src/api/public/media/media.controller.ts
  src/app.module.ts
  src/main.ts
  src/media/backends/filesystem-backend.ts
  src/media/media.service.ts
  src/notes/notes.service.ts
  src/users/user.entity.ts
  test/public-api/fixtures/test.png
  test/public-api/media.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
  yarn.lock
Labels: enhancement

#512 Updates for the public API
  docs/dev/public_api.yml
  src/history/history.service.ts
  src/notes/note-metadata.dto.ts
  src/notes/note-permissions.dto.ts
  src/notes/notes.service.ts
Labels: enhancement
