Repository hedgedoc/hedgedoc, pull requests merged in 2020-08, with the labels that each got.

#464 feat: add default values to configuration documentation
  docs/configuration.md
Labels: documentation

#468 [1.x] Fix: Set moment.js locale to users' locale (#275)
  locales/en.json
  public/js/extra.js
  public/js/locale.js
  public/views/codimd/body.ejs
Labels: bug, frontend

#469 Update Webpack dependencies
  package.json
  webpack.common.js
  yarn.lock
Labels: enhancement
