Repository hedgedoc/hedgedoc, pull requests merged in 2020-09, with the labels that each got.

#490 Document the backup process
  README.md
Labels: documentation, enhancement

#480 Add E2E tests for /notes route
  test/jest-e2e.json
  test/public-api/notes.e2e-spec.ts
Labels: public API

#486 [1.x] Add config option for cookie SameSite policy
  app.js
  app.json
  config.json.example
  docs/configuration.md
  lib/config/default.js
  lib/config/environment.js
  lib/config/index.js
  lib/web/statusRouter.js
  public/js/index.js
  public/js/lib/common/constant.ejs
  public/js/lib/common/login.js
  public/js/lib/editor/index.js
  public/js/locale.js
Labels: enhancement

#497 [1.x] Add Malayalam translation
  app.js
  locales/ml.json
  public/views/index/body.ejs
Labels: enhancement

#500 Implement /notes route
  docs/dev/db-schema.plantuml
  docs/dev/public_api.yml
  package.json
  src/api/public/me/me.controller.spec.ts
  src/api/public/notes/notes.controller.spec.ts
  src/api/public/notes/notes.controller.ts
  src/notes/note.dto.ts
  src/notes/note.entity.ts
  src/notes/note.utils.ts
  src/notes/notes.module.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/revisions/revision-metadata.dto.ts
  src/revisions/revision.dto.ts
  src/revisions/revision.entity.ts
  src/revisions/revisions.module.ts
  src/revisions/revisions.service.spec.ts
  src/revisions/revisions.service.ts
  src/users/users.service.ts
  test/public-api/notes.e2e-spec.ts
  yarn.lock
Labels: public API

#496 [1.x] Update matrix chat link from riot.im to app.element.io
  README.md
  SECURITY.md
  public/docs/features.md
  public/views/index/body.ejs
  public/views/shared/help-modal.ejs
Labels: documentation, enhancement, frontend
