Repository hedgedoc/hedgedoc, pull requests merged in 2020-02, with the labels that each got.

#266 Update CDN defaults
  docs/configuration-config-file.md
  lib/config/default.js
Labels: enhancement

#264 Update mermaid
  package.json
  public/views/codimd/foot.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
Labels: enhancement

#267 Fix revision redirect to index page
  public/js/index.js
Labels: bug

#258 Remove mattermost integration
  README.md
  app.json
  config.json.example
  docs/configuration-config-file.md
  docs/configuration-env-vars.md
  docs/guides/auth/oauth.md
  lib/app.js
  lib/config/default.js
  lib/config/dockerSecret.js
  lib/config/environment.js
  lib/config/hackmdEnvironment.js
  lib/config/index.js
  lib/models/user.js
  lib/web/auth/index.js
  lib/web/auth/mattermost/index.js
  package.json
  public/docs/privacy.md.example
  public/views/index/body.ejs
  public/views/shared/signin-modal.ejs
Labels: breaking, enhancement
