Repository hedgedoc/hedgedoc, pull requests merged in 2021-08, with the labels that each got.

#1468 [1.x] Exclude /metrics and /status routes from session initialization
  app.js
  lib/utils.js
Labels: priority: medium, type: bug

#1474 [1.x] Add help link and short explanation for failing migrations
  lib/models/index.js
Labels: type: enhancement

#1505 fix(s3): replace dash with dot for s3 endpoint
  lib/web/imageRouter/s3.js
Labels: priority: medium, status: confirmed, type: bug

#1544 fix(image-upload): Fix swallowing of errors for filesystem
  lib/web/imageRouter/filesystem.js
Labels: type: enhancement

#1540 Fix crash while getting current git commit
  lib/config/utils.js
  public/docs/release-notes.md
Labels: type: bug

#1542 Docs: Use Postgres 13 in Docker example
  docs/content/setup/docker.md
Labels: type: documentation, type: maintenance

#1543 Automatically retry DB connection on startup
  app.js
  public/docs/release-notes.md
Labels: type: feature

#1537 Remove redundant `ws` dependency
  app.js
  package.json
  yarn.lock
Labels: type: maintenance

#1541 Various CI updates
  .github/workflows/node.js.yml
Labels: type: maintenance

#1533 feat(config): Improve configurability of database by env
  docs/content/configuration.md
  lib/config/environment.js
Labels: type: enhancement

#1545 Fix endless loop on shutdown when DB can't be reached
  app.js
  public/docs/release-notes.md
Labels: type: bug

#1546 Fix unescaped line break in `git` output
  lib/config/utils.js
Labels: type: bug

#1513 Tighten up Content-Security-Policy
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  lib/csp.js
  public/docs/release-notes.md
  public/js/extra.js
  test/csp.js
Labels: type: enhancement

#1538 Set secure flag for non-session cookies
  public/docs/release-notes.md
  public/js/index.js
  public/js/lib/common/login.js
  public/js/lib/editor/index.js
  public/js/locale.js
Labels: type: bug

#1539 Cleanup ESLint config
  .eslintrc.js
Labels: type: maintenance

#1394 Remove cdn support
  README.md
  app.js
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  lib/config/hackmdEnvironment.js
  lib/config/oldDefault.js
  lib/csp.js
  public/css/google-font.css
  public/js/extra.js
  public/js/htmlExport.js
  public/views/hedgedoc/footer.ejs
  public/views/hedgedoc/head.ejs
  public/views/htmlexport.ejs
  public/views/index/footer.ejs
  public/views/index/head.ejs
  public/views/pretty.ejs
  public/views/shared/polyfill.ejs
  public/views/slide.ejs
  test/csp.js
  webpack.common.js
  webpack.htmlexport.js
  webpack.prod.js
Labels: type: enhancement

#1536 Introduce changelog snippets
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: type: enhancement, type: documentation

#1532 Port over the FAQ page from hedgedoc.org to docs.hedgedoc.org
  docs/content/faq.md
  docs/content/index.md
  docs/mkdocs.yml
Labels: type: documentation

#1559 Ignore local installed fonts
  public/css/font.css
  public/docs/release-notes.md
Labels: type: enhancement, scope: frontend

#1562 Release 1.9.0-rc1
  docs/content/dev/openapi.yml
  package.json
  public/docs/release-notes.md
  yarn.lock
Labels: type: enhancement
