Repository hedgedoc/hedgedoc, pull requests merged in 2021-03, with the labels that each got.

#969 [1.x] Run database migrations automatically on startup
  app.js
  docs/content/guides/migration-troubleshooting.md
  docs/mkdocs.yml
  lib/models/index.js
  package.json
  yarn.lock
Labels: type: enhancement

#997 Documentation updates after #969
  .sequelizerc.example
  bin/heroku
  bin/setup
  docs/content/setup/manual-setup.md
  public/docs/release-notes.md
Labels: type: documentation

#975 Docs: Add Azure, Filesystem, Imgur and S3
  docs/content/media/azure.md
  docs/content/media/filesystem.md
  docs/content/media/imgur.md
  docs/content/media/s3.md
Labels: type: documentation

#1025 [1.x] Dependencies: Replace deprecated request library with node-fetch
  lib/response.js
  package.json
  yarn.lock
Labels: type: maintenance

#1059 PublicE2E: Remove uploaded files after test
  test/public-api/me.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: bug

#1083 Properly clean up socket on exit
  app.js
Labels: type: bug

#1084 Check for existing notes on POST and don't override them
  lib/errors.js
  lib/web/note/util.js
Labels: type: bug

#1088 CSP: Remove yahoo domain from defaults
  lib/csp.js
Labels: type: enhancement
