Repository hedgedoc/hedgedoc, pull requests merged in 2021-04, with the labels that each got.

#1091 [Docs] Add "HedgeDoc flavored markdown" page
  docs/content/references/hfm.md
  docs/mkdocs.yml
Labels: priority: medium, type: documentation

#1102 Fix emoji replacement in SAML docs
  docs/content/guides/auth/saml.md
Labels: type: documentation

#1101 Add missing mkdocs plugin + Replace unicode character
  docs/content/references/hfm.md
  docs/mkdocs.yml
Labels: type: documentation

#1114 Update CHANGELOG.md to point to releases page
  CHANGELOG.md
Labels: type: documentation

#984 Improvements to installation docs
  docs/content/guides/migrations-and-breaking-changes.md
  docs/content/setup/docker.md
  docs/content/setup/getting-started.md
  docs/content/setup/manual-setup.md
  docs/mkdocs.yml
Labels: type: documentation

#1144 Add clear getting started instructions to README
  README.md
Labels: type: documentation

#1166 CI: Run tests with Node.js 16 [master]
  .github/workflows/node.js.yml
Labels: type: maintenance

#1169 Media E2E tests: Add error handling for upload cleanup
  test/private-api/media.e2e-spec.ts
  test/public-api/media.e2e-spec.ts
  test/utils.ts
Labels: type: bug

#1170 FilesystemBackend: Fix functionContext logging
  src/media/backends/filesystem-backend.ts
Labels: type: bug

#1117 Use upstream imgur library
  lib/web/imageRouter/imgur.js
  package.json
  public/docs/release-notes.md
  yarn.lock
Labels: type: enhancement

#1168 CI: Run tests with Node.js 16 [develop]
  .github/workflows/nest.js.yml
Labels: type: maintenance

#1167 Raise minimum required Node.js version to 12 [master]
  .github/workflows/node.js.yml
  bin/setup
  docs/content/setup/manual-setup.md
  package.json
  public/docs/release-notes.md
Labels: type: maintenance

#1150 Add Prometheus endpoint
  app.js
  docs/content/dev/api.md
  lib/prometheus.js
  package.json
  public/docs/release-notes.md
  yarn.lock
Labels: type: feature

#1187 Remove banner from frontend config
  .gitignore
  public/.gitkeep
  src/frontend-config/frontend-config.dto.ts
  src/frontend-config/frontend-config.service.spec.ts
  src/frontend-config/frontend-config.service.ts
  src/main.ts
Labels: scope: private API, type: enhancement

#1193 Fix logo link in README.md
  README.md
Labels: type: documentation

#1201 [1.x] Remove unneeded polyfill
  lib/models/user.js
  package.json
  yarn.lock
Labels: type: maintenance
