Repository hedgedoc/hedgedoc, pull requests merged in 2021-12, with the labels that each got.

#1853 feat: get note interceptor
  src/api/private/me/history/history.controller.ts
  src/api/private/notes/notes.controller.ts
  src/api/public/me/me.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/get-note.interceptor.ts
  src/api/utils/permissions.guard.ts
  src/api/utils/request-note.decorator.ts
Labels: type: feature

#1857 Exclude /status, /metrics from session middleware
  app.js
  public/docs/release-notes.md
Labels: type: bug, priority: critical

#1874 Codecov: Wait for 2 builds to be submitted
  codecov.yml
Labels: type: maintenance

#1818 CI: Setup njsscan
  .github/workflows/njsscan-analysis.yml
Labels: type: maintenance

#1878 Correctly check for missing session
  src/identity/session.guard.ts
Labels: type: bug

#1879 docs/reverse-proxy: align NC
  docs/content/guides/reverse-proxy.md
Labels: type: documentation

#1882 fix(auth): use sha-512 for auth tokens
  docs/content/dev/2.0.md
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  test/private-api/tokens.e2e-spec.ts
Labels: type: bug

#1795 Add Docs for getting started with 2.0
  docs/content/dev/2.0.md
  docs/content/dev/getting-started.md
Labels: type: documentation
