Repository hedgedoc/hedgedoc, pull requests merged in 2021-01, with the labels that each got.

#650 Documentation with mkdocs
  .gitignore
  docs/dev/documentation.md
  docs/dev/getting-started.md
  docs/images/favicon.png
  docs/images/logo.png
  docs/index.md
  mkdocs.requirements.txt
  mkdocs.yml
Labels: priority: high, type: documentation

#652 Update docs for 2.0 development
  CONTRIBUTING.md
  README.md
Labels: type: documentation

#659 Several theme changes
  docs/content/theme/styles/Roboto/roboto-latin-regular.woff
  docs/content/theme/styles/Roboto/roboto-latin-regular.woff2
  docs/content/theme/styles/Roboto/roboto-mono-latin-regular.woff
  docs/content/theme/styles/Roboto/roboto-mono-latin-regular.woff2
  docs/content/theme/styles/hedgedoc-custom.css
  docs/content/theme/styles/roboto.css
  docs/mkdocs.yml
Labels: priority: high, type: documentation

#663 Add CI workflow
  .github/workflows/nest.js.yml
  .gitignore
  README.md
  package.json
  src/api/utils/markdownbody-decorator.ts
  src/monitoring/monitoring.service.ts
  src/revisions/authorship.entity.ts
  test/public-api/users.e2e-spec.ts
Labels: type: maintenance

#667 Cherry-Pick: Several theme changes (#659)
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  docs/content/theme/styles/Roboto/roboto-latin-regular.woff
  docs/content/theme/styles/Roboto/roboto-latin-regular.woff2
  docs/content/theme/styles/Roboto/roboto-mono-latin-regular.woff
  docs/content/theme/styles/Roboto/roboto-mono-latin-regular.woff2
  docs/content/theme/styles/hedgedoc-custom.css
  docs/content/theme/styles/roboto.css
  docs/mkdocs.yml
Labels: priority: high, type: documentation

#671 Update Renovate config
  renovate.json
Labels: type: maintenance

#691 Renovate: group all packages under @nestjs
  renovate.json
Labels: type: maintenance

#695 Renovate: Maintain lock files once per week
  renovate.json
Labels: type: maintenance

#703 NotesController: Do not crash on nonexistent notes
  src/api/public/notes/notes.controller.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: bug

#708 MarkdownBody: Register swagger metadata
  src/api/utils/markdownbody-decorator.ts
Labels: type: enhancement

#707 Get note creation time from database
  src/notes/notes.service.ts
  src/revisions/revisions.service.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#722 Various documentation improvements
  docs/content/guides/auth/github.md
  docs/content/guides/auth/gitlab-self-hosted.md
  docs/content/guides/auth/keycloak.md
  docs/content/guides/auth/ldap-ad.md
  docs/content/guides/auth/mattermost-self-hosted.md
  docs/content/guides/auth/nextcloud.md
  docs/content/guides/auth/saml-keycloak.md
  docs/content/guides/auth/saml-onelogin.md
  docs/content/guides/auth/saml.md
  docs/content/guides/auth/twitter.md
  docs/content/guides/minio-image-upload.md
  docs/content/guides/s3-image-upload.md
  docs/mkdocs.yml
  docs/requirements.txt
Labels: type: documentation

#735 Delete slide options that are not defined
  public/js/slide.js
Labels: priority: critical, type: bug

#709 Notes API: Improve spec compliance
  docs/content/dev/public_api.yml
  src/api/public/notes/notes.controller.ts
  src/notes/notes.service.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: bug, type: enhancement

#741 Add page to setup namespace
  docs/content/setup/index.md
Labels: type: documentation

#750 [Documentation] Fix link in manual setup
  docs/content/setup/manual-setup.md
Labels: priority: high, type: bug

#766 Add JSDoc comments to DTOs
  nest-cli.json
  src/history/history-entry-update.dto.ts
  src/history/history-entry.dto.ts
  src/notes/note-authorship.dto.ts
  src/notes/note-metadata.dto.ts
  src/notes/note-permissions.dto.ts
  src/notes/note.dto.ts
  src/revisions/revision-metadata.dto.ts
  src/revisions/revision.dto.ts
  src/users/user-info.dto.ts
Labels: type: documentation

#755 Add config option which requires authentication in FreeURL mode
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  lib/web/note/util.js
Labels: priority: medium, type: enhancement

#768 Swagger: Split public and private API
  src/main.ts
  src/utils/swagger.ts
Labels: type: documentation

#779 Improved CSS in night-mode
  public/css/markdown.css
Labels: scope: frontend, type: enhancement

#790 Add issue config to add external links to the community forum
  .github/ISSUE_TEMPLATE/config.yml
  .reuse/dep5
Labels: type: enhancement
