Repository hedgedoc/hedgedoc, pull requests merged in 2021-09, with the labels that each got.

#1610 Fix usage of "HFM" in table headers
  docs/content/references/hfm.md
Labels: type: documentation, priority: low

#1588 Introduce RequestUser decorator
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/request-user.decorator.ts
  types/express/index.d.ts
Labels: type: enhancement

#1589 Introduce GetNotePipe
  src/api/private/me/history/history.controller.ts
  src/api/private/media/media.controller.ts
  src/api/private/notes/notes.controller.ts
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/media/media.service.spec.ts
  src/media/media.service.ts
  src/notes/get-note.pipe.ts
  src/notes/notes.service.ts
  src/revisions/revisions.service.ts
  test/private-api/history.e2e-spec.ts
  test/private-api/me.e2e-spec.ts
  test/private-api/notes.e2e-spec.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/media.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#1633 Refactor existing code to add the configured domain to connect-src
  lib/config/buildDomainOriginWithProtocol.js
  lib/config/index.js
  lib/csp.js
  public/docs/release-notes.md
Labels: type: bug

#1663 Add missing title property to issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: type: bug

#1664 Update security.md to match state in master branch
  SECURITY.md
Labels: type: documentation

#1616 Switch to Yarn Berry
  .github/workflows/nest.js.yml
  .gitignore
  .prettierrc
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-typescript.cjs
  .yarn/releases/yarn-berry.cjs
  .yarn/releases/yarn-berry.cjs.license
  .yarnrc.yml
  .yarnrc.yml.license
  LICENSES/BSD-2-Clause.txt
  package.json
  src/frontend-config/frontend-config.dto.ts
  src/frontend-config/frontend-config.service.ts
  src/media/backends/s3-backend.ts
  src/media/backends/webdav-backend.ts
  tsconfig.json
  yarn.lock
Labels: type: maintenance
