Repository hedgedoc/hedgedoc, pull requests merged in 2021-05, with the labels that each got.

#1218 Update meta-marked
  yarn.lock
Labels: type: maintenance

#1234 Fix click handler for numbered task lists
  public/js/extra.js
Labels: scope: frontend, type: bug

#1226 Move frontend-only deps to devDependencies
  bin/setup
  package.json
Labels: type: enhancement

#1233 Fix insertOnStartOfLines behaviour
  public/js/lib/editor/utils.js
Labels: type: bug

#1222 Fix upgradeInsecureRequests CSP directive
  lib/csp.js
Labels: priority: critical, type: bug

#1223 Automatically enable protocolUseSSL when useSSL is set
  lib/config/index.js
Labels: priority: medium, type: bug

#1227 Use esbuild to minify frontend JS
  .babelrc
  package.json
  webpack.prod.js
  yarn.lock
Labels: type: enhancement

#1246 Ignore Postgres SSL errors on Heroku
  bin/heroku
Labels: type: bug

#1207 Enable TypeScript strict mode
  jest-e2e.json
  package.json
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/markdownbody-decorator.ts
  src/auth/auth-token.dto.ts
  src/auth/auth-token.entity.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/config/app.config.ts
  src/config/database.config.ts
  src/config/hsts.config.ts
  src/config/utils.spec.ts
  src/config/utils.ts
  src/frontend-config/frontend-config.dto.ts
  src/groups/groups.service.spec.ts
  src/groups/groups.service.ts
  src/history/history.service.ts
  src/logger/console-logger.service.ts
  src/main.ts
  src/media/media-upload.dto.ts
  src/media/media-upload.entity.ts
  src/media/media.service.ts
  src/notes/note-metadata.dto.ts
  src/notes/note-permissions.dto.ts
  src/notes/note.entity.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/revisions/revisions.service.spec.ts
  src/revisions/revisions.service.ts
  src/seed.ts
  src/users/identity.entity.ts
  src/users/user.entity.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/private-api/history.e2e-spec.ts
  test/public-api/media.e2e-spec.ts
  tsconfig.json
  tsconfig.test.json
  tsconfig.test.json.license
Labels: type: enhancement, type: maintenance

#1257 Remove superfluous overrideProvider statements
  src/api/private/notes/notes.controller.spec.ts
  src/media/media.service.spec.ts
Labels: type: enhancement

#1258 AuthTokenEntity: Make validUntil not nullable
  src/auth/auth-token.dto.ts
  src/auth/auth-token.entity.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
Labels: type: bug

#1282 Replace vimeo meta data api
  public/js/extra.js
Labels: type: bug

#1180 Add API decorator to reduce clutter
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/fullapi-decorator.ts
Labels: scope: public API, type: enhancement

#1319 Move publicId creation to Note.create
  src/notes/note.entity.ts
  src/notes/notes.service.ts
  src/notes/utils.ts
Labels: type: bug

#1266 Allow anonymous user colors
  docs/content/dev/db-schema.plantuml
  src/api/private/me/history/history.controller.spec.ts
  src/api/private/me/me.controller.spec.ts
  src/api/private/media/media.controller.spec.ts
  src/api/private/notes/notes.controller.spec.ts
  src/api/private/tokens/tokens.controller.spec.ts
  src/api/public/me/me.controller.spec.ts
  src/api/public/media/media.controller.spec.ts
  src/api/public/notes/notes.controller.spec.ts
  src/auth/auth.service.spec.ts
  src/authors/author.entity.ts
  src/history/history.service.spec.ts
  src/media/media.service.spec.ts
  src/notes/author-color.entity.ts
  src/notes/note.entity.ts
  src/notes/notes.module.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/permissions/permissions.service.spec.ts
  src/revisions/authorship.entity.ts
  src/revisions/revisions.module.ts
  src/revisions/revisions.service.spec.ts
  src/seed.ts
  src/users/session.entity.ts
  src/users/user.entity.ts
  src/users/users.module.ts
Labels: type: enhancement

#1344 Rename Authorship entity to Edit
  src/api/private/me/history/history.controller.spec.ts
  src/api/private/me/me.controller.spec.ts
  src/api/private/media/media.controller.spec.ts
  src/api/private/notes/notes.controller.spec.ts
  src/api/public/me/me.controller.spec.ts
  src/api/public/media/media.controller.spec.ts
  src/api/public/notes/notes.controller.spec.ts
  src/authors/author.entity.ts
  src/history/history.service.spec.ts
  src/media/media.service.spec.ts
  src/notes/note.dto.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/permissions/permissions.service.spec.ts
  src/revisions/edit.dto.ts
  src/revisions/edit.entity.ts
  src/revisions/revision.entity.ts
  src/revisions/revisions.module.ts
  src/revisions/revisions.service.spec.ts
  src/seed.ts
Labels: type: enhancement
