Repository hedgedoc/hedgedoc, pull requests merged in 2021-06, with the labels that each got.

#1346 Add Cloudflare warning to the docs
  docs/content/guides/reverse-proxy.md
Labels: type: documentation

#1350 Remove explicit title from cloudflare warning
  docs/content/guides/reverse-proxy.md
Labels: type: documentation

#1360 Fix link in openapi doc
  docs/content/dev/openapi.yml
Labels: type: documentation

#1368 Remove script-loader
  package.json
  public/js/extra.js
  public/js/index.js
  public/js/lib/editor/index.js
  public/vendor/abcjs_basic_3.1.1-min.js
  public/vendor/jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png
  public/vendor/jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png
  public/vendor/jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png
  public/vendor/jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png
  public/vendor/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png
  public/vendor/jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png
  public/vendor/jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png
  public/vendor/jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  public/vendor/jquery-ui/images/ui-icons_222222_256x240.png
  public/vendor/jquery-ui/images/ui-icons_2e83ff_256x240.png
  public/vendor/jquery-ui/images/ui-icons_454545_256x240.png
  public/vendor/jquery-ui/images/ui-icons_888888_256x240.png
  public/vendor/jquery-ui/images/ui-icons_cd0a0a_256x240.png
  public/vendor/jquery-ui/jquery-ui.min.css
  public/vendor/jquery-ui/jquery-ui.min.js
  webpack.common.js
  yarn.lock
Labels: scope: frontend, type: enhancement

#1375 Disable GA and Disqus in default CSP
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  public/docs/release-notes.md
  test/csp.js
Labels: security, type: enhancement

#1371 Webpack: production source maps & split chunks
  webpack.prod.js
Labels: scope: frontend, type: enhancement

#1369 Remove unsafe-eval from default CSP
  lib/csp.js
  webpack.dev.js
Labels: scope: frontend, type: enhancement

#1370 Lazy-load various frontend-libraries
  package.json
  public/js/extra.js
  public/js/index.js
  public/views/hedgedoc/footer.ejs
  public/views/pretty.ejs
  public/views/slide.ejs
  webpack.common.js
  yarn.lock
Labels: scope: frontend, type: enhancement
