Repository hedgedoc/hedgedoc, pull requests merged in 2021-11, with the labels that each got.

#1794 feat: initialise special groups on bootstrap
  src/groups/groups.service.spec.ts
  src/groups/groups.service.ts
  src/groups/groups.special.ts
  src/main.ts
  src/permissions/permissions.service.spec.ts
  src/permissions/permissions.service.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  src/utils/createSpecialGroups.ts
Labels: type: feature

#1817 CI: Test and build with Node 17
  .github/workflows/nest.js.yml
  .yarn/releases/yarn-3.1.0.cjs
  .yarn/releases/yarn-3.1.0.cjs.license
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: type: maintenance

#1826 Run E2E tests concurrently
  package.json
  src/config/mock/media.config.mock.ts
Labels: type: enhancement

#1680 fix: create methods
  docs/content/dev/2.0.md
  src/api/private/notes/notes.controller.ts
  src/api/public/notes/notes.controller.ts
  src/auth/auth-token.entity.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/authors/author.entity.ts
  src/groups/group.entity.ts
  src/groups/groups.service.spec.ts
  src/groups/groups.service.ts
  src/history/history-entry.entity.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/history/utils.spec.ts
  src/identity/identity.entity.ts
  src/identity/identity.service.spec.ts
  src/identity/identity.service.ts
  src/media/media-upload.entity.ts
  src/media/media.service.spec.ts
  src/media/media.service.ts
  src/notes/alias.entity.ts
  src/notes/alias.service.spec.ts
  src/notes/alias.service.ts
  src/notes/note.entity.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/notes/utils.spec.ts
  src/permissions/note-group-permission.entity.ts
  src/permissions/note-user-permission.entity.ts
  src/permissions/permissions.service.spec.ts
  src/revisions/edit.entity.ts
  src/revisions/revision.entity.ts
  src/revisions/revisions.service.spec.ts
  src/seed.ts
  src/users/user.entity.ts
  test/private-api/alias.e2e-spec.ts
  test/private-api/history.e2e-spec.ts
  test/private-api/me.e2e-spec.ts
  test/private-api/media.e2e-spec.ts
  test/private-api/notes.e2e-spec.ts
  test/public-api/alias.e2e-spec.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/media.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#1825 Update RenovateBot config
  renovate.json
Labels: type: maintenance

#1829 Add new FAQ section "Why does my interface look weird?"
  docs/content/faq.md
  docs/content/faq/interface_broken.png
  docs/content/faq/interface_okay.png
  docs/content/guides/reverse-proxy.md
Labels: type: documentation

#1851 Add missing null in type in permissions service
  src/permissions/permissions.service.ts
Labels: type: bug
