Repository hedgedoc/hedgedoc, pull requests merged in 2021-02, with the labels that each got.

#787 Add commit guidelines to contribution docs
  CONTRIBUTING.md
Labels: type: enhancement

#789 Docs: Emphasize the difference between branches
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: type: documentation

#803 renovatebot: Configure renovatebot to update 1.x and 2.x branches
  renovate.json
Labels: type: enhancement

#800 Fix wrong acces to slide options
  public/js/slide.js
Labels: priority: high, scope: frontend, type: bug

#802 Extend setup page with community methods
  docs/content/guides/reverse-proxy.md
  docs/content/setup/arch-linux.md
  docs/content/setup/index.md
  docs/content/setup/kubernetes-helm.md
  docs/content/setup/kubernetes.md
  docs/mkdocs.yml
Labels: priority: medium, type: enhancement

#829 [Docs] Add "getting started" page
  docs/content/setup/getting-started.md
  docs/content/theme/styles/hedgedoc-custom.css
  docs/mkdocs.yml
Labels: priority: medium, type: documentation

#801 History: Add history routes in /me
  docs/content/dev/db-schema.plantuml
  src/api/private/tokens/tokens.controller.ts
  src/api/public/me/me.controller.spec.ts
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/monitoring/monitoring.controller.ts
  src/api/public/notes/notes.controller.spec.ts
  src/api/public/notes/notes.controller.ts
  src/auth/auth.service.spec.ts
  src/auth/mock-auth.guard.ts
  src/history/history-entry.dto.ts
  src/history/history-entry.entity.ts
  src/history/history.module.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/notes/note.entity.ts
  src/notes/notes.service.ts
  src/users/user.entity.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/users.e2e-spec.ts
Labels: scope: public API, type: feature

#844 Add missing logging context at various places
  src/api/public/notes/notes.controller.ts
  src/auth/auth.service.ts
  src/notes/notes.service.ts
Labels: type: enhancement

#798 Fix note creation in FreeURL-mode does not apply default template
  lib/models/note.js
Labels: type: bug

#863 Fix link to sequelize docs for database dialects
  docs/content/configuration.md
Labels: priority: high, status: confirmed, type: documentation

#860 More Webpack loader updates
  package.json
  yarn.lock
Labels: type: maintenance

#926 Add HTTP 404 error on actions for non-existent notes
  lib/web/note/controller.js
  lib/web/note/util.js
Labels: type: enhancement

#932 Document supported databases
  docs/content/dev/2.0.md
Labels: type: documentation

#936 Stronger ESLint rules
  .eslintrc.js
  package.json
  src/api/private/tokens/tokens.controller.ts
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/monitoring/monitoring.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/markdownbody-decorator.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/mock-auth.guard.ts
  src/config/app.config.ts
  src/config/auth.config.ts
  src/config/csp.config.ts
  src/config/database.config.ts
  src/config/hsts.config.ts
  src/config/media.config.ts
  src/config/utils.spec.ts
  src/config/utils.ts
  src/groups/groups.service.spec.ts
  src/groups/groups.service.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/logger/console-logger.service.ts
  src/logger/nest-console-logger.service.ts
  src/main.ts
  src/media/backends/filesystem-backend.ts
  src/media/media.service.spec.ts
  src/monitoring/monitoring.service.ts
  src/monitoring/server-status.dto.ts
  src/notes/note.entity.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/permissions/permissions.service.spec.ts
  src/users/users.service.ts
  src/utils/swagger.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/media.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
  types/express/index.d.ts
  yarn.lock
Labels: type: maintenance
