Repository hedgedoc/hedgedoc, pull requests merged in 2022-12, with the labels that each got.

#2976 fix(ci): fix concurrency of ci runs if triggered by pull_request_target
  .github/workflows/frontend-e2e-tests.yml
  .github/workflows/frontend-netlify-deploy-pr.yml
Labels: type: ci/cd

#2728 fix(realtime): Allow connections for guest users
  backend/src/realtime/realtime-note/realtime-note.ts
  backend/src/realtime/realtime-note/test-utils/mock-connection.ts
  backend/src/realtime/realtime-note/websocket-connection.spec.ts
  backend/src/realtime/realtime-note/websocket-connection.ts
  backend/src/realtime/websocket/websocket.gateway.spec.ts
  backend/src/realtime/websocket/websocket.gateway.ts
  backend/src/session/session.service.spec.ts
  backend/src/session/session.service.ts
Labels: type: bug

#3033 fix(frontend): migrate TOC to @hedgedoc/markdown-it-plugins
  frontend/package.json
  frontend/src/components/editor-page/table-of-contents/table-of-contents.test.tsx
  frontend/src/components/editor-page/table-of-contents/table-of-contents.tsx
  frontend/src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
  frontend/src/components/markdown-renderer/extensions/table-of-contents-markdown-extension.ts
  frontend/src/components/render-page/document-toc-sidebar.tsx
  frontend/src/components/render-page/markdown-toc-button/table-of-contents-hovering-button.tsx
  frontend/src/components/render-page/width-based-table-of-contents.tsx
  frontend/src/extensions/extra-integrations/task-list/task-list-markdown-extension.ts
  yarn.lock
Labels: type: feature enhancement

#3065 chore: Add resolution for codemirror/autocompletion
  package.json
  yarn.lock
Labels: type: maintenance

#3068 fix(frontend): Fix i18n types
  frontend/src/components/common/links/translated-external-link.tsx
  frontend/src/components/common/links/translated-internal-link.tsx
  frontend/src/components/common/links/types.d.ts
  frontend/src/components/notifications/ui-notification-boundary.tsx
Labels: type: bug

#3089 fix(i18n): clarify where to find /features for new users
  frontend/CHANGELOG.md
  frontend/locales/en.json
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
Labels: type: feature enhancement
