Repository hedgedoc/hedgedoc, pull requests merged in 2022-06, with the labels that each got.

#2376 Speed up FrontendConfig tests
  src/frontend-config/frontend-config.service.spec.ts
Labels: type: maintenance

#2416 ci: drop Node.js 12
  .github/workflows/nest.js.yml
Labels: type: maintenance

#2415 docs: add info about unsupported CAs and node
  docs/content/configuration.md
  docs/content/guides/auth/nextcloud.md
Labels: type: documentation

#2454 test(e2e/app): disable debug logging
  test/app.e2e-spec.ts
Labels: type: enhancement

#2453 Extract common app setup code
  src/app-init.ts
  src/main.ts
  test/test-setup.ts
Labels: type: enhancement
