Repository hedgedoc/hedgedoc, pull requests merged in 2022-02, with the labels that each got.

#2067 Add error message to log if database cannot be reached
  app.js
  public/docs/release-notes.md
Labels: type: enhancement

#2075 test: remove controller tests
  src/api/private/alias/alias.controller.spec.ts
  src/api/private/auth/auth.controller.spec.ts
  src/api/private/config/config.controller.spec.ts
  src/api/private/me/history/history.controller.spec.ts
  src/api/private/me/me.controller.spec.ts
  src/api/private/media/media.controller.spec.ts
  src/api/private/notes/notes.controller.spec.ts
  src/api/private/tokens/tokens.controller.spec.ts
  src/api/public/alias/alias.controller.spec.ts
  src/api/public/me/me.controller.spec.ts
  src/api/public/media/media.controller.spec.ts
  src/api/public/monitoring/monitoring.controller.spec.ts
  src/api/public/notes/notes.controller.spec.ts
Labels: scope: public API, scope: private API

#2146 fix(session-middleware): don't hardcode database TTL
  src/utils/session.ts
Labels: type: bug
