Repository hedgedoc/hedgedoc, pull requests merged in 2022-08, with the labels that each got.

#2584 Add dark mode toggle in mobile view
  public/docs/release-notes.md
  public/views/hedgedoc/header.ejs
Labels: type: enhancement, scope: frontend

#2583 Fix crash in LDAP authentication
  lib/web/auth/ldap/index.js
  public/docs/release-notes.md
Labels: type: bug

#2587 Replace embedding regex with more specific ones
  public/docs/release-notes.md
  public/js/extra.js
Labels: type: enhancement
