Repository hedgedoc/hedgedoc, pull requests merged in 2022-05, with the labels that each got.

#2277 Refactor NoteService unit tests
  src/notes/notes.service.spec.ts
Labels: type: enhancement

#2309 [1.x] Drop Node 12
  .github/workflows/node.js.yml
  bin/setup
  docs/content/setup/manual-setup.md
  package.json
  public/docs/release-notes.md
Labels: type: maintenance

#2335 [Docs] Fix heroku missing logo and non-required env var
  app.json
Labels: type: documentation

#2377 fix(revision-service): fix count of duplicate authors
  src/revisions/revisions.service.spec.ts
  src/revisions/revisions.service.ts
Labels: type: bug
