Repository hedgedoc/hedgedoc, pull requests merged in 2022-01, with the labels that each got.

#1827 Lazy-load all relations
  src/api/private/alias/alias.controller.ts
  src/api/private/me/history/history.controller.ts
  src/api/private/me/me.controller.ts
  src/api/private/media/media.controller.ts
  src/api/private/notes/notes.controller.ts
  src/api/public/alias/alias.controller.ts
  src/api/public/me/me.controller.ts
  src/api/public/media/media.controller.ts
  src/api/public/notes/notes.controller.ts
  src/api/utils/permissions.guard.ts
  src/auth/auth-token.entity.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/authors/author.entity.ts
  src/groups/group.entity.ts
  src/history/history-entry.entity.ts
  src/history/history.service.spec.ts
  src/history/history.service.ts
  src/history/utils.spec.ts
  src/history/utils.ts
  src/identity/identity.entity.ts
  src/identity/identity.service.spec.ts
  src/media/media-upload.entity.ts
  src/media/media.service.spec.ts
  src/media/media.service.ts
  src/notes/alias.entity.ts
  src/notes/alias.service.spec.ts
  src/notes/alias.service.ts
  src/notes/note.entity.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  src/notes/tag.entity.ts
  src/notes/utils.spec.ts
  src/notes/utils.ts
  src/permissions/note-group-permission.entity.ts
  src/permissions/note-user-permission.entity.ts
  src/permissions/permissions.service.spec.ts
  src/permissions/permissions.service.ts
  src/revisions/edit.entity.ts
  src/revisions/revision.entity.ts
  src/seed.ts
  src/users/session.entity.ts
  src/users/user.entity.ts
  test/private-api/history.e2e-spec.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#1934 Frontend-Config: Array of enabled auth providers
  src/frontend-config/frontend-config.dto.ts
  src/frontend-config/frontend-config.service.spec.ts
  src/frontend-config/frontend-config.service.ts
Labels: type: enhancement

#1935 Auth: Require old password for password change
  src/api/private/auth/auth.controller.ts
  src/identity/identity.service.spec.ts
  src/identity/identity.service.ts
  src/identity/local/local.strategy.ts
  src/identity/local/update-password.dto.ts
  test/private-api/auth.e2e-spec.ts
  test/private-api/register-and-login.e2e-spec.ts
Labels: type: enhancement

#1938 Fix(logger): Ignore docker health check requests
  app.js
Labels: type: enhancement

#1955 Use libravatar image if email address is defined
  lib/letter-avatars.js
  lib/models/user.js
  lib/web/auth/oauth2/index.js
  public/docs/release-notes.md
  test/letter-avatars.js
Labels: type: bug

#1985 API docs: Add missing tags
  src/api/private/alias/alias.controller.ts
  src/api/private/auth/auth.controller.ts
  src/api/private/config/config.controller.ts
  src/api/private/me/me.controller.ts
  src/api/private/media/media.controller.ts
  src/api/private/notes/notes.controller.ts
Labels: type: documentation

#1986 Consistently name timestamp attributes
  src/auth/auth-token.dto.ts
  src/auth/auth-token.entity.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/history/history-entry.dto.ts
  src/history/history.service.ts
  src/notes/note-metadata.dto.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  test/private-api/history.e2e-spec.ts
  test/private-api/tokens.e2e-spec.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#1987 Do not embed User/Group objects
  src/notes/note-metadata.dto.ts
  src/notes/note-permissions.dto.ts
  src/notes/notes.service.spec.ts
  src/notes/notes.service.ts
  test/public-api/me.e2e-spec.ts
  test/public-api/notes.e2e-spec.ts
Labels: type: enhancement

#1953 Documentation & working example for Authelia OAuth SSO
  docs/content/guides/auth/authelia.md
Labels: type: documentation
