Repository hedgedoc/hedgedoc, pull requests merged in 2022-04, with the labels that each got.

#2240 docs: add example for generating sessionSecret
  docs/content/configuration.md
Labels: type: documentation

#2243 Improve aria tags for view mode labels
  public/views/hedgedoc/header.ejs
Labels: type: enhancement

#2242 Force change of aria-hidden when modal shows or hides
  public/docs/release-notes.md
  public/js/cover.js
  public/js/fix-aria-hidden-for-modals.js
  public/js/index.js
Labels: type: enhancement

#2249 Fix missing inline authorship colors
  public/.eslintrc.js
  public/docs/release-notes.md
  public/js/index.js
  public/vendor/ot/hex2rgb.js
Labels: type: bug, priority: high

#2273 fix(console-logger): don't sanitize colors away
  src/logger/console-logger.service.ts
Labels: type: bug

#2274 fix(notes): primaryAddress reveals internal UUID
  src/notes/notes.service.ts
Labels: type: bug
