Repository hedgedoc/hedgedoc, pull requests merged in 2023-01, with the labels that each got.

#2843 Set the session cookie after registering
  backend/src/api/private/auth/auth.controller.ts
Labels: type: feature enhancement

#3145 misc(ci): pin dependencies of GitHub actions
  .github/actions/setup-node/action.yml
  .github/workflows/backend-docker-cleanup.yml
  .github/workflows/backend-docker.yml
  .github/workflows/backend-e2e-tests.yml
  .github/workflows/backend-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/commons-lint.yml
  .github/workflows/commons-tests.yml
  .github/workflows/frontend-docker.yml
  .github/workflows/frontend-e2e-tests.yml
  .github/workflows/frontend-lint.yml
  .github/workflows/frontend-netlify-deploy-main.yml
  .github/workflows/frontend-netlify-deploy-pr.yml
  .github/workflows/frontend-test-and-build.yml
  .github/workflows/njsscan-analysis.yml
  .github/workflows/reuse.yml
Labels: type: maintenance

#3149 fix(redux): avoid state mutation in history redux
  frontend/src/components/editor-page/hooks/use-update-local-history-entry.ts
Labels: type: bug, scope: frontend

#3144 fix(tests): syntax for loop in console-logger service
  backend/src/logger/console-logger.service.spec.ts
Labels: type: bug

#3219 config: Add a flag to control the /metrics and /status endpoints
  app.js
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  public/docs/release-notes.md
Labels: type: feature enhancement
