Repository hedgedoc/hedgedoc, pull requests merged in 2023-04, with the labels that each got.

#3755 feat(renderer): Add intermediate class for markdown renderer extensions with event emitter
  frontend/src/components/markdown-renderer/extensions/base/event-markdown-renderer-extension.ts
  frontend/src/components/markdown-renderer/extensions/base/markdown-renderer-extension.ts
  frontend/src/components/markdown-renderer/extensions/table-of-contents/table-of-contents-markdown-extension.ts
  frontend/src/components/markdown-renderer/hooks/use-markdown-extensions.ts
  frontend/src/extensions/base/app-extension.ts
  frontend/src/extensions/extra-integrations/task-list/task-list-markdown-extension.ts
Labels: type: code quality enhancement

#3756 fix: use callback hook in checkbox editor component to cache function
  frontend/src/extensions/extra-integrations/task-list/set-checkbox-in-cheatsheet.tsx
Labels: type: bug

#3769 fix: fix permissions in mocked feature page
  frontend/src/pages/api/private/notes/features/index.ts
Labels: type: bug

#3781 fix: suppress yjs double import warning
  .yarn/patches/yjs-npm-13.5.52-a5c64d9068.patch
  package.json
  yarn.lock
Labels: type: feature enhancement

#3794 fix deprecated netlify plugin
  .github/workflows/frontend-netlify-deploy-main.yml
  .github/workflows/frontend-netlify-deploy-pr.yml
  renovate.json
Labels: type: bug, ci: force deployment

#3806 Disconnect message transporter on editor leave
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts
Labels: type: bug

#3711 refactor: create mock function for noteRepo and eventemiter
  backend/src/permissions/permissions.service.spec.ts
Labels: type: code quality enhancement

#3842 fix caching of e2e test
  .github/workflows/e2e-tests.yml
Labels: type: bug, type: ci/cd

#3817 Only show non-guest users in the sidebar #2953
  frontend/locales/en.json
  frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.tsx
Labels: type: feature

#3852 fix: render toc button only if toc is available
  frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
Labels: type: bug

#3853 fix: sticky position of toc sidebar
  frontend/global-styles/index.scss
  frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
  frontend/src/components/render-page/renderers/document/markdown-document.module.scss
  frontend/src/components/render-page/renderers/document/width-based-table-of-contents.tsx
Labels: type: bug

#3882 fix: height of loading screen
  frontend/src/components/application-loader/application-loader.module.scss
  frontend/src/components/application-loader/loading-screen/loading-screen.tsx
Labels: type: bug, ci: force deployment

#3879 chore: fix and reformat editorconfig
  frontend/.editorconfig
Labels: type: maintenance

#3876 feat(frontend): increase reconnect timeout with every try
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts
Labels: type: feature

#3898 chore: fix yjs patch
  .yarn/patches/yjs-remove-import-warning-in-test.patch
  package.json
  yarn.lock
Labels: type: maintenance
