Repository hedgedoc/hedgedoc, pull requests merged in 2023-03, with the labels that each got.

#3425 fix(docker): fix yarn cache folder
  backend/docker/Dockerfile
  frontend/docker/Dockerfile
Labels: type: feature enhancement

#3454 feat(editor): extract the spell check codemirror extension into separate hook
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/code-mirror-extensions/use-code-mirror-spell-check-extension.ts
Labels: type: code quality enhancement

#3453 fix(turbo): add npm task for test:ci
  package.json
Labels: type: code quality enhancement

#3452 feat(frontend): add size property to wait spinner component
  frontend/src/components/common/wait-spinner/wait-spinner.tsx
Labels: type: feature enhancement

#3451 fix(frontend): extract codemirror extension for ref update into hook
  frontend/src/components/editor-page/change-content-context/change-content-context.tsx
  frontend/src/components/editor-page/change-content-context/codemirror-reference-context.tsx
  frontend/src/components/editor-page/change-content-context/use-change-editor-content-callback.tsx
  frontend/src/components/editor-page/editor-page-content.tsx
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/image-upload-from-renderer/use-on-image-upload-from-renderer.ts
  frontend/src/components/editor-page/editor-pane/hooks/use-apply-scroll-state.ts
  frontend/src/components/editor-page/editor-pane/hooks/use-handle-upload.tsx
  frontend/src/components/editor-page/editor-pane/hooks/use-update-code-mirror-reference.ts
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/bold-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/check-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/code-fence-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/collapsible-block-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/comment-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/header-level-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/highlight-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/horizontal-line-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/image-link-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/italic-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/link-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/ordered-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/quotes-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/strikethrough-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/subscript-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/superscript-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/underline-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/unordered-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/toolbar-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/upload-image-button/upload-image-button.tsx
Labels: type: code quality enhancement

#3457 fix(dev-reverse-proxy): try to run global caddy first
  dev-reverse-proxy/package.json
Labels: type: feature enhancement

#3520 Turn html/markdown to react converters from hook to component
  frontend/src/components/common/html-to-react/__snapshots__/html-to-react.test.tsx.snap
  frontend/src/components/common/html-to-react/html-to-react.test.tsx
  frontend/src/components/common/html-to-react/html-to-react.tsx
  frontend/src/components/markdown-renderer/document-markdown-renderer.tsx
  frontend/src/components/markdown-renderer/extensions/image-placeholder/image-placeholder-markdown-extension.ts
  frontend/src/components/markdown-renderer/extensions/linemarker/types.d.ts
  frontend/src/components/markdown-renderer/extensions/sanitizer/dom-purifier-node-preprocessor.ts
  frontend/src/components/markdown-renderer/extensions/sanitizer/sanitizer-markdown-extension.ts
  frontend/src/components/markdown-renderer/extensions/table-of-contents-markdown-extension.ts
  frontend/src/components/markdown-renderer/hooks/use-calculate-line-marker-positions.ts
  frontend/src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.tsx
  frontend/src/components/markdown-renderer/hooks/use-markdown-extensions.ts
  frontend/src/components/markdown-renderer/markdown-to-react/__snapshots__/markdown-to-react.test.tsx.snap
  frontend/src/components/markdown-renderer/markdown-to-react/hooks/use-combined-node-preprocessor.ts
  frontend/src/components/markdown-renderer/markdown-to-react/hooks/use-configured-markdown-it.ts
  frontend/src/components/markdown-renderer/markdown-to-react/markdown-to-react.test.tsx
  frontend/src/components/markdown-renderer/markdown-to-react/markdown-to-react.tsx
  frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-markdown-renderer-extension.ts
  frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-node-processor.ts
  frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-replacer.tsx
  frontend/src/components/markdown-renderer/markdown-to-react/utils/line-content-to-line-id-mapper.test.ts
  frontend/src/components/markdown-renderer/markdown-to-react/utils/line-content-to-line-id-mapper.ts
  frontend/src/components/markdown-renderer/markdown-to-react/utils/node-to-react-transformer.test.tsx
  frontend/src/components/markdown-renderer/markdown-to-react/utils/node-to-react-transformer.tsx
  frontend/src/components/markdown-renderer/slideshow-markdown-renderer.tsx
  frontend/src/components/markdown-renderer/test-utils/test-markdown-renderer.tsx
  frontend/src/components/render-page/hooks/sync-scroll/use-document-sync-scrolling.ts
  frontend/src/components/render-page/markdown-document.tsx
  frontend/src/extensions/extra-integrations/highlighted-code-fence/hooks/use-code-dom.tsx
  frontend/src/extensions/extra-integrations/plantuml/plantuml-markdown-extension.ts
Labels: type: feature enhancement

#3534 chore(ci): update cypress/browsers image in e2e workflow
  .github/workflows/e2e-tests.yml
Labels: type: maintenance

#3548 refactor(frontend): reorganize html head elements
  frontend/src/components/editor-page/head-meta-properties/opengraph-head.tsx
Labels: type: feature enhancement

#3554 fix: replace bootstrap icon html with utf-8 icon
  frontend/src/components/markdown-renderer/extensions/headline-anchors-markdown-extension.ts
Labels: type: bug

#3450 [1.x] Add /_health endpoint
  app.js
  lib/web/statusRouter.js
  public/docs/release-notes.md
Labels: type: feature enhancement

#3555 fix: change sessionstate type to prevent unset values
  backend/src/api/private/auth/auth.controller.ts
  backend/src/api/utils/session-authprovider.decorator.ts
  backend/src/identity/session.guard.ts
  backend/src/realtime/websocket/websocket.gateway.ts
  backend/src/session/session.service.spec.ts
  backend/src/session/session.service.ts
Labels: type: bug

#3560 fix: exclude the link icon from the first heading extraction text
  frontend/global-styles/markdown-tweaks.scss
  frontend/src/components/markdown-renderer/hooks/use-extract-first-headline.ts
Labels: type: bug

#3606 fix: prevent splitter panels from being selected when resizing
  frontend/src/components/editor-page/splitter/splitter.module.scss
  frontend/src/components/editor-page/splitter/splitter.tsx
Labels: type: bug

#3607 refactor: save ydoc state in the database, so it can be restored easier
  backend/src/realtime/realtime-note/realtime-connection.spec.ts
  backend/src/realtime/realtime-note/realtime-connection.ts
  backend/src/realtime/realtime-note/realtime-note-store.spec.ts
  backend/src/realtime/realtime-note/realtime-note-store.ts
  backend/src/realtime/realtime-note/realtime-note.service.spec.ts
  backend/src/realtime/realtime-note/realtime-note.service.ts
  backend/src/realtime/realtime-note/realtime-note.spec.ts
  backend/src/realtime/realtime-note/realtime-note.ts
  backend/src/revisions/revision.entity.ts
  backend/src/revisions/revisions.service.ts
  commons/src/message-transporters/mocked-backend-message-transporter.ts
  commons/src/y-doc-sync/realtime-doc.test.ts
  commons/src/y-doc-sync/realtime-doc.ts
  commons/src/y-doc-sync/y-doc-sync-adapter.test.ts
  commons/src/y-doc-sync/y-doc-sync-adapter.ts
  commons/src/y-doc-sync/y-doc-sync-client-adapter.ts
  commons/src/y-doc-sync/y-doc-sync-server-adapter.ts
  frontend/src/components/editor-page/editor-pane/codemirror-extensions/document-sync/y-text-sync-view-plugin.ts
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-bind-y-text-to-redux.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-code-mirror-yjs-extension.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-markdown-content-y-text.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-doc.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-y-doc-sync-client-adapter.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-y-doc.ts
Labels: type: feature

#3627 feat: submit own user data on realtime user state set
  backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
  backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
  commons/src/message-transporters/message.ts
  frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/receive-remote-cursor-view-plugin.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-receive-realtime-users.ts
  frontend/src/redux/realtime/methods.ts
  frontend/src/redux/realtime/reducers.ts
  frontend/src/redux/realtime/types.ts
Labels: type: feature enhancement

#3492 CodeMirror autocompletion
  frontend/locales/en.json
  frontend/src/components/editor-page/editor-pane/autocompletions/basic-completion.ts
  frontend/src/components/editor-page/editor-pane/autocompletions/regex-completion.ts
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/codemirror-extensions/use-code-mirror-autocompletions-extension.ts
  frontend/src/components/markdown-renderer/extensions/basic-markdown-syntax/basic-markdown-syntax-app-extension.ts
  frontend/src/components/markdown-renderer/extensions/bootstrap-icons/bootstrap-icon-app-extension.ts
  frontend/src/components/markdown-renderer/extensions/emoji/emoji-app-extension.ts
  frontend/src/components/markdown-renderer/extensions/emoji/mapping.ts
  frontend/src/components/markdown-renderer/extensions/image-placeholder/image-placeholder-app-extension.ts
  frontend/src/components/markdown-renderer/extensions/table-of-contents/table-of-contents-app-extension.ts
  frontend/src/extensions/base/app-extension.ts
  frontend/src/extensions/extra-integrations/abcjs/abcjs-app-extension.ts
  frontend/src/extensions/extra-integrations/alert/alert-app-extension.ts
  frontend/src/extensions/extra-integrations/blockquote/blockquote-app-extension.ts
  frontend/src/extensions/extra-integrations/csv/csv-table-app-extension.ts
  frontend/src/extensions/extra-integrations/flowchart/flowchart-app-extension.ts
  frontend/src/extensions/extra-integrations/graphviz/graphviz-app-extension.ts
  frontend/src/extensions/extra-integrations/highlighted-code-fence/highlighted-code-fence-app-extension.ts
  frontend/src/extensions/extra-integrations/mermaid/mermaid-app-extension.ts
  frontend/src/extensions/extra-integrations/plantuml/plantuml-app-extension.ts
  frontend/src/extensions/extra-integrations/spoiler/spoiler-app-extension.ts
  frontend/src/extensions/extra-integrations/vega-lite/vega-lite-app-extension.ts
Labels: type: feature, ci: force deployment, feature: editor

#3628 fix: useTranslation hook in react components
  frontend/src/components/editor-page/editor-pane/hooks/use-handle-upload.tsx
  frontend/src/components/layout/settings-dialog/settings-modal.tsx
  frontend/src/components/notifications/ui-notification-boundary.tsx
Labels: type: bug, type: code quality enhancement

#3630 build: add eslint rule forbidding TypeORM Equal constructor
  backend/.eslintrc.js
  eslint-local-rules.js
Labels: type: code quality enhancement

#3638 fix: use correct callback on websocket error
  commons/src/message-transporters/websocket-transporter.ts
Labels: type: bug

#3642 fix: disconnect websocket if trying to send over closed connection
  commons/src/message-transporters/websocket-transporter.ts
Labels: type: bug

#3673 fix(backend): keep log output in dev mode
  backend/tsconfig.json
Labels: type: feature enhancement

#3677 feat(realtime): synchronize and show realtime activity state
  backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
  commons/src/message-transporters/message.ts
  frontend/locales/en.json
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-send-realtime-activity.ts
  frontend/src/components/editor-page/sidebar/user-line/user-line.module.scss
  frontend/src/components/editor-page/sidebar/user-line/user-line.tsx
  frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.module.scss
  frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.tsx
  frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/own-user-line.tsx
Labels: type: feature enhancement

#3710 fix(turbo): ignore webpack cache
  turbo.json
Labels: type: bug
