Repository hedgedoc/hedgedoc, pull requests merged in 2023-02, with the labels that each got.

#3251 Revert "config: Add a flag to control the /metrics and /status endpoints"
  app.js
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  public/docs/release-notes.md
Labels: type: bug

#3271 fix(commons): remove redundant tsconfig for eslint
  commons/.eslintrc.cjs
  commons/jest.config.json
  commons/tsconfig-eslint.json
  commons/tsconfig-eslint.json.license
  commons/tsconfig.json
Labels: type: code quality enhancement

#3275 fix(ci): Add write permissions for push of frontend image to ghcr
  .github/workflows/frontend-docker.yml
Labels: type: ci/cd

#3288 fix(frontend): simplify asciinema regex
  frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.test.ts
  frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.ts
Labels: type: feature enhancement

#3292 fix(ci): fix docker build args
  .github/workflows/docker.yml
Labels: type: ci/cd

#3293 fix(docker): fix workspace focus command
  frontend/docker/Dockerfile
Labels: type: ci/cd

#3294 fix(docker): Separate docker builds into two jobs
  .github/workflows/docker.yml
Labels: type: ci/cd

#3295 chore(deps): pin dependencies of commons package
  backend/package.json
  commons/package.json
  yarn.lock
Labels: type: maintenance

#3296 fix(commons): extract name of markdown content yjs channel into the commons package
  backend/src/realtime/realtime-note/websocket-doc.ts
  commons/src/constants/markdown-content-channel-name.ts
  commons/src/index.ts
  commons/src/y-doc-message-transporter.test.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/mock-connection.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-markdown-content-y-text.ts
Labels: type: feature enhancement

#3289 Typed event emitter
  .yarn/patches/eventemitter2-npm-6.4.9-ba37798a18.patch
  backend/src/events.ts
  backend/src/notes/notes.service.ts
  backend/src/permissions/permissions.service.ts
  backend/src/realtime/realtime-note/realtime-note.ts
  backend/src/realtime/realtime-note/test-utils/mock-realtime-note.ts
  frontend/src/components/common/note-loading-boundary/hooks/use-load-note-from-server.ts
  frontend/src/components/editor-page/app-bar/help-button/cheatsheet-line.tsx
  frontend/src/components/markdown-renderer/extensions/base/markdown-renderer-extension.ts
  frontend/src/components/markdown-renderer/hooks/use-extension-event-emitter.tsx
  frontend/src/components/render-page/iframe-markdown-renderer.tsx
  frontend/src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
  frontend/src/extensions/base/app-extension.ts
  frontend/src/extensions/extra-integrations/task-list/task-list-checkbox-app-extension.ts
  package.json
  yarn.lock
Labels: type: code quality enhancement

#3328 fix(image-router): correct usage of rimraf
  lib/web/imageRouter/index.js
Labels: type: bug

#3335 fix(bundle): force esbuild-loader to use cjs instead of iife
  webpack.prod.js
Labels: type: bug

#3336 feat(bundle): add webpack clean plugin
  package.json
  webpack.common.js
  yarn.lock
Labels: type: feature enhancement

#3348 fix(tests): add license field to frontmatter
  frontend/src/redux/note-details/reducers/build-state-from-set-note-data-from-server.test.ts
Labels: type: bug, scope: frontend

#3370 feat(docs): activate search plugin
  docs/mkdocs.yml
Labels: type: documentation

#3374 fix(night-mode): migrate cookie solution to store only and simplify code
  public/docs/release-notes.md
  public/js/index.js
  public/js/lib/appState.js
Labels: type: bug

#3376 refactor(ci): restructure workflows
  .github/actions/setup-node/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
Labels: type: ci/cd

#3377 fix(frontend): use "action" prop in revisions list
  frontend/global-styles/variables.dark.scss
  frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.module.scss
  frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.tsx
Labels: type: feature enhancement, ci: force deployment

#3379 Update OCI labels in 2.0 docker images
  backend/docker/Dockerfile
  frontend/docker/Dockerfile
Labels: type: code quality enhancement

#3380 fix(frontend): replace blockquote extra e2e test with unit test
  frontend/cypress/e2e/quote-extra.spec.ts
  frontend/src/extensions/extra-integrations/blockquote/__snapshots__/blockquote-extra-tag-markdown-extension.test.tsx.snap
  frontend/src/extensions/extra-integrations/blockquote/blockquote-extra-tag-markdown-extension.test.tsx
Labels: type: code quality enhancement

#3383 fix(docs): reformat hfm.md
  docs/content/references/hfm.md
Labels: type: documentation
