Repository hedgedoc/hedgedoc, pull requests merged in 2023-05, with the labels that each got.

#3945 fix(backend): fix extraction body values in permission controllers
  backend/src/api/private/notes/notes.controller.ts
  backend/src/api/public/notes/notes.controller.ts
  frontend/src/api/permissions/index.ts
  frontend/src/api/permissions/types.ts
Labels: type: bug

#3975 fix(editor): catch error when refreshing note metadata
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-on-metadata-updated.ts
Labels: type: bug

#3987 chore(ci): update cypress browsers image
  .github/workflows/e2e-tests.yml
Labels: type: maintenance

#3974 fix(realtime): allow realtime user status updates from users that have read-only access
  backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
  backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
  commons/src/message-transporters/realtime-user.ts
  frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/receive-remote-cursor-view-plugin.ts
Labels: type: feature enhancement

#3986 chore: change recommended and CI node version to v20
  .github/workflows/e2e-tests.yml
  .github/workflows/frontend-netlify-deploy-main.yml
  .github/workflows/frontend-netlify-deploy-pr.yml
  .github/workflows/lint.yml
  .github/workflows/test-and-build.yml
  backend/package.json
  docs/content/dev/getting-started.md
  frontend/package.json
  yarn.lock
Labels: type: maintenance

#4016 fix: use html entity for branding separation dash
  frontend/src/components/common/custom-branding/custom-branding.tsx
  frontend/src/components/common/custom-branding/use-branding-details.ts
  frontend/src/components/editor-page/app-bar/branding-separator-dash.tsx
  frontend/src/components/editor-page/app-bar/branding.module.scss
  frontend/src/components/editor-page/app-bar/navbar-branding.tsx
Labels: type: bug

#4042 Revert "chore(deps): update dependency turbo to v1.9.4"
  package.json
  yarn.lock
Labels: type: maintenance

#4104 fix: height of reveal rendering
  frontend/src/components/render-page/renderers/slideshow/slideshow-markdown-renderer.tsx
  frontend/src/components/render-page/renderers/slideshow/slideshow.module.scss
Labels: type: bug

#3924 Fix premature note cleanup on error
  lib/realtime.js
  public/docs/release-notes.md
Labels: type: bug, priority: 2. medium

#4114 fix(webpack): give reveal.js's marked.js a 'exports' variable
  public/docs/release-notes.md
  webpack.common.js
Labels: type: bug

#4132 refactor: reorganize files in commons package
  commons/src/frontmatter-extractor/index.ts
  commons/src/index.ts
  commons/src/message-transporters/index.ts
  commons/src/note-frontmatter-parser/convert-raw-frontmatter-to-note-frontmatter.ts
  commons/src/note-frontmatter-parser/index.ts
  commons/src/note-frontmatter-parser/parse-raw-frontmatter-from-yaml.ts
  commons/src/note-frontmatter-parser/types.ts
  commons/src/note-frontmatter/default-values.ts
  commons/src/note-frontmatter/index.ts
  commons/src/parse-url/errors.ts
  commons/src/parse-url/index.ts
  commons/src/parse-url/parse-url.spec.ts
  commons/src/parse-url/parse-url.ts
  commons/src/permissions/index.ts
  commons/src/permissions/permissions.spec.ts
  commons/src/permissions/permissions.ts
  commons/src/permissions/permissions.types.ts
  commons/src/title-extraction/index.ts
  commons/src/utils/wait-for-other-promises-to-finish.ts
  commons/src/y-doc-sync/index.ts
  commons/types/reveal.d.ts
  frontend/src/components/common/note-loading-boundary/create-non-existing-note-hint.spec.tsx
  frontend/src/external-types/reveal.js/index.d.ts
Labels: type: code quality enhancement
