Repository hedgedoc/hedgedoc, pull requests merged in 2023-10, with the labels that each got.

#5007 remove dropbox, facebook & twitter login
  backend/CHANGELOG.md
  backend/src/config/auth.config.ts
  backend/src/config/mock/auth.config.mock.ts
  backend/src/frontend-config/frontend-config.dto.ts
  backend/src/frontend-config/frontend-config.service.spec.ts
  backend/src/frontend-config/frontend-config.service.ts
  backend/src/identity/identity.entity.ts
  backend/src/identity/provider-type.enum.ts
  docs/content/concepts/api-auth.md
  docs/content/theme/styles/hedgedoc-custom.css
  frontend/cypress/support/config.ts
  frontend/src/api/config/types.ts
  frontend/src/components/login-page/one-click/get-one-click-provider-metadata.ts
  frontend/src/components/login-page/one-click/via-one-click.module.scss
  frontend/src/pages/api/private/config.ts
Labels: feature: auth

#5023 fix: use correct import for identicon
  frontend/src/components/common/user-avatar/hooks/use-avatar-url.ts
Labels: type: bug

#5030 fix: redirect to history page after register to avoid problems
  frontend/src/components/login-page/local-login/register/local-register-form.tsx
Labels: type: bug

#4938 Docs: Add a warning about an NGINX pitfall and its symptom in HedgeDoc
  docs/content/guides/reverse-proxy.md
Labels: type: documentation

#5048 fix(codemirror): remove defect language highlighting
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
Labels: type: bug

#5051 fix(editor): fix emoji picker data path
  frontend/src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-popover.tsx
Labels: type: bug

#5053 fix(editor): fix positions of tag migration lint
  frontend/src/components/editor-page/editor-pane/linter/frontmatter-linter.spec.ts
  frontend/src/components/editor-page/editor-pane/linter/frontmatter-linter.ts
Labels: type: bug

#5055 fix: rename "last updated at" sidebar entry
  frontend/locales/en.json
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/note-info-sidebar-menu/note-info-line/note-info-line-updated-at.tsx
Labels: type: feature enhancement

#5058 ci: build docker images for tags
  .github/workflows/docker.yml
Labels: type: maintenance

#5069 docs: add readme note about docs.hedgedoc.dev
  README.md
Labels: type: documentation

#5098 chore(deps): use the same ts-node version in frontend/backend
  backend/package.json
  frontend/package.json
  yarn.lock
Labels: type: maintenance

#5120 enhancement(autocomplete): add generic code suggestion entry
  frontend/src/extensions/essential-app-extensions/highlighted-code-fence/highlighted-code-fence-app-extension.ts
Labels: type: feature enhancement, feature: editor

#5116 feat(sidebar): distinguish guest users visually
  frontend/locales/en.json
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/active-indicator.module.scss
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/active-indicator.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/user-line/user-line.tsx
Labels: type: feature enhancement, feature: editor

#5125 enhancement(notifications): remove from state after dismissal
  frontend/src/components/notifications/ui-notification-boundary.tsx
  frontend/src/components/notifications/ui-notification-toast.tsx
  frontend/src/components/notifications/ui-notifications.tsx
  frontend/src/test-utils/mock-ui-notifications.ts
Labels: type: feature enhancement

#5151 fix(i18n): wrong translation key for max length
  frontend/locales/en.json
Labels: type: bug

#4757 fix(oauth2): Fix crash in rolesClaim extraction
  lib/web/auth/oauth2/index.js
Labels: type: bug

#5182 fix(frontend): error in review viewer
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-viewer.tsx
Labels: type: bug
