Repository hedgedoc/hedgedoc, pull requests merged in 2023-06, with the labels that each got.

#4131 refactor: extract height monitor hook
  frontend/src/components/render-page/hooks/use-on-height-change.ts
  frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
  frontend/src/components/render-page/renderers/simple/simple-markdown-renderer.tsx
Labels: type: code quality enhancement

#4130 refactor: extract visual part of the toolbar-button component and use it in all buttons components
  frontend/cypress/e2e/fileUpload.spec.ts
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/bold-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/check-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/code-fence-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/collapsible-block-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/comment-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/header-level-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/highlight-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/horizontal-line-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/image-link-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/italic-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/link-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/ordered-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/quotes-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/strikethrough-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/subscript-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/superscript-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/underline-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/buttons/unordered-list-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/formatter-toolbar-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.module.scss
  frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-size-picker-popover.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/toolbar-button.tsx
  frontend/src/components/editor-page/editor-pane/tool-bar/upload-image-button/upload-image-button.tsx
Labels: ci: force deployment, type: code quality enhancement

#4133 refactor: remove isomorphic-ws
  backend/src/realtime/realtime-note/realtime-connection.spec.ts
  backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
  backend/src/realtime/realtime-note/test-utils/mock-connection.ts
  backend/src/realtime/websocket/backend-websocket-adapter.spec.ts
  backend/src/realtime/websocket/backend-websocket-adapter.ts
  backend/src/realtime/websocket/websocket.gateway.ts
  commons/package.json
  commons/src/index.ts
  commons/src/message-transporters/index.ts
  commons/src/message-transporters/message-transporter.ts
  commons/src/message-transporters/mocked-backend-message-transporter.ts
  commons/src/message-transporters/mocked-backend-transport-adapter.ts
  commons/src/message-transporters/transport-adapter.ts
  commons/src/message-transporters/websocket-transporter.ts
  commons/src/utils/index.ts
  commons/src/utils/wait-for-other-promises-to-finish.ts
  commons/src/y-doc-sync/in-memory-connection-message.transporter.ts
  frontend/package.json
  frontend/src/components/common/note-loading-boundary/create-non-existing-note-hint.spec.tsx
  frontend/src/components/editor-page/editor-pane/hooks/yjs/frontend-websocket-adapter.spec.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/frontend-websocket-adapter.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts
  yarn.lock
Labels: type: bug, type: code quality enhancement

#4156 Configure Renovate to pin versions
  renovate.json
Labels: type: maintenance

#4161 fix(esbuild): exclude reveal.js marked plugin
  webpack.common.js
  webpack.prod.js
Labels: type: bug

#4162 fix: macOS compatibility for bin/setup
  bin/setup
  public/docs/release-notes.md
Labels: type: bug

#4165 enhancement(metrics): allow disabling via config option
  app.js
  docs/content/configuration.md
  lib/config/default.js
  lib/config/environment.js
  lib/web/statusRouter.js
  public/docs/release-notes.md
Labels: type: feature enhancement

#4243 chore: adjust patched yjs version
  renovate.json
Labels: type: ci/cd

#4260 deps(ci): update cypress browsers docker image
  .github/workflows/e2e-tests.yml
Labels: type: maintenance

#4277 feat: replace placeholder icons of gitlab, matrix and discourse
  frontend/src/components/common/icons/additional/icon-discourse.tsx
  frontend/src/components/common/icons/additional/icon-gitlab.tsx
  frontend/src/components/common/icons/additional/icon-matrix-org.tsx
  frontend/src/components/editor-page/app-bar/help-button/links-tab-content.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/import-menu-sidebar-menu.tsx
  frontend/src/components/landing-layout/footer/social-links.tsx
  frontend/src/components/login-page/auth/utils/get-one-click-provider-metadata.ts
Labels: type: feature enhancement

#4308 fix(backend): immediately use our custom logger
  backend/src/main.ts
Labels: type: bug

#4310 fix(frontend): fix event emitter leak in realtime status
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-send-realtime-activity.ts
Labels: type: feature enhancement

#4329 enhancement: add profiling flag to analyze run
  frontend/next.config.js
  frontend/package.json
  frontend/src/utils/test-modes.js
Labels: type: feature enhancement

#4331 fix(backend): prevent zombie realtime connections
  backend/src/realtime/websocket/websocket.gateway.ts
Labels: type: bug

#4339 fix(communication): send ready event when both sides are ready
  backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
  backend/src/realtime/websocket/backend-websocket-adapter.spec.ts
  backend/src/realtime/websocket/websocket.gateway.ts
  commons/src/message-transporters/message-transporter.ts
  commons/src/message-transporters/message.ts
  commons/src/message-transporters/mocked-backend-transport-adapter.ts
  commons/src/y-doc-sync/in-memory-connection-message.transporter.ts
  commons/src/y-doc-sync/in-memory-connection-transport-adapter.ts
  commons/src/y-doc-sync/y-doc-sync-adapter.spec.ts
  frontend/src/components/editor-page/editor-pane/editor-pane.tsx
  frontend/src/components/editor-page/editor-pane/hooks/yjs/frontend-websocket-adapter.spec.ts
Labels: type: bug

#4355 Use note title with fallback in deletion modal
  frontend/cypress/e2e/deleteNote.spec.ts
  frontend/src/components/editor-page/editor-pane/hooks/yjs/use-on-note-deleted.ts
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/delete-note-sidebar-entry/delete-note-modal.tsx
Labels: type: bug
