Repository hedgedoc/hedgedoc, pull requests merged in 2023-09, with the labels that each got.

#4776 Revert "fix: replace class BaseUrlFromEnvExtractor"
  frontend/src/app/(editor)/[id]/page.tsx
  frontend/src/app/(editor)/layout.tsx
  frontend/src/app/(render)/layout.tsx
  frontend/src/middleware.ts
  frontend/src/utils/base-url-from-env-extractor.spec.ts
  frontend/src/utils/base-url-from-env-extractor.ts
Labels: type: feature enhancement

#4778 fix: extract app bar into layout slot
  frontend/src/app/(editor)/@appBar/cheatsheet/page.tsx
  frontend/src/app/(editor)/@appBar/default.tsx
  frontend/src/app/(editor)/@appBar/history/page.tsx
  frontend/src/app/(editor)/@appBar/intro/page.tsx
  frontend/src/app/(editor)/@appBar/login/page.tsx
  frontend/src/app/(editor)/@appBar/n/[noteId]/__snapshots__/editor-app-bar.spec.tsx.snap
  frontend/src/app/(editor)/@appBar/n/[noteId]/editor-app-bar.spec.tsx
  frontend/src/app/(editor)/@appBar/n/[noteId]/editor-app-bar.tsx
  frontend/src/app/(editor)/@appBar/n/[noteId]/page.tsx
  frontend/src/app/(editor)/@appBar/not-found.tsx
  frontend/src/app/(editor)/@appBar/p/[noteId]/page.tsx
  frontend/src/app/(editor)/@appBar/profile/page.tsx
  frontend/src/app/(editor)/@appBar/register/page.tsx
  frontend/src/app/(editor)/@appBar/s/[noteId]/page.tsx
  frontend/src/app/(editor)/history/page.tsx
  frontend/src/app/(editor)/intro/page.tsx
  frontend/src/app/(editor)/layout.tsx
  frontend/src/app/(editor)/s/[noteId]/page.tsx
  frontend/src/components/editor-page/editor-page-content.tsx
  frontend/src/components/editor-page/sidebar/sidebar-menu/sidebar-menu.module.scss
  frontend/src/components/intro-page/cover-buttons/cover-buttons.module.scss
  frontend/src/components/intro-page/cover-buttons/cover-buttons.tsx
  frontend/src/components/landing-layout/landing-layout.tsx
  frontend/src/components/landing-layout/navigation/header-bar/header-bar.tsx
  frontend/src/components/landing-layout/navigation/header-bar/header-nav-link.module.scss
  frontend/src/components/landing-layout/navigation/header-bar/header-nav-link.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/branding-element.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/branding-separator-dash.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/help-dropdown/help-dropdown.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/help-dropdown/history-button.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/note-title-element/note-title-element.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/user-element.tsx
  frontend/src/components/layout/app-bar/base-app-bar.tsx
  frontend/src/components/layout/app-bar/navbar.module.scss
  frontend/src/components/render-page/hooks/use-on-height-change.ts
Labels: type: feature

#4810 fix: improve deep partial type used in tests
  commons/src/utils/deep-partial.ts
  commons/src/utils/index.ts
  frontend/src/test-utils/mock-app-state.ts
  frontend/src/test-utils/mock-note-permissions.ts
Labels: type: feature enhancement

#4822 fix(frontend): show reconnect alert only if note has been loaded
  frontend/src/app/(editor)/@appBar/n/[noteId]/editor-app-bar.tsx
Labels: type: feature enhancement

#4826 ci: remove node 16
  .github/workflows/test-and-build.yml
Labels: type: ci/cd

#4825 ci: remove node 16
  .github/workflows/build-and-test.yml
Labels: type: ci/cd

#4918 fix(backend): fix target directory of dist directory
  backend/docker/Dockerfile
Labels: type: feature enhancement

#4923 feat: merge login and intro page
  frontend/cypress/e2e/history.spec.ts
  frontend/cypress/e2e/intro.spec.ts
  frontend/cypress/e2e/signInButton.spec.ts
  frontend/cypress/support/config.ts
  frontend/cypress/support/e2e.ts
  frontend/cypress/support/logout.ts
  frontend/locales/en.json
  frontend/next.config.js
  frontend/src/app/(editor)/@appBar/intro/page.tsx
  frontend/src/app/(editor)/@appBar/login/page.tsx
  frontend/src/app/(editor)/intro/page.tsx
  frontend/src/app/(editor)/login/page.tsx
  frontend/src/app/(editor)/register/page.tsx
  frontend/src/components/application-loader/initializers/index.ts
  frontend/src/components/landing-layout/navigation/sign-in-button.tsx
  frontend/src/components/layout/app-bar/app-bar-elements/help-dropdown/help-dropdown.tsx
  frontend/src/components/layout/app-bar/base-app-bar.tsx
  frontend/src/components/login-page/auth/fields/fields.ts
  frontend/src/components/login-page/guest/guest-card.tsx
  frontend/src/components/login-page/ldap/ldap-login-card.tsx
  frontend/src/components/login-page/ldap/ldap-login-cards.tsx
  frontend/src/components/login-page/local-login/local-login-card-body.tsx
  frontend/src/components/login-page/local-login/local-login-card.tsx
  frontend/src/components/login-page/local-login/register/local-register-button.tsx
  frontend/src/components/login-page/local-login/register/local-register-card-body.tsx
  frontend/src/components/login-page/local-login/register/local-register-form.tsx
  frontend/src/components/login-page/one-click/get-one-click-provider-metadata.ts
  frontend/src/components/login-page/one-click/one-click-login-button.tsx
  frontend/src/components/login-page/one-click/one-click-login-card.tsx
  frontend/src/components/login-page/one-click/via-one-click.module.scss
  frontend/src/components/login-page/password-field.tsx
  frontend/src/components/login-page/redirect-to-param-or-history.tsx
  frontend/src/components/login-page/utils/fetch-and-set-user.ts
  frontend/src/components/login-page/utils/filter-one-click-providers.ts
  frontend/src/components/profile-page/settings/profile-display-name.tsx
  frontend/src/pages/api/private/auth/local/login.ts
  frontend/src/pages/api/private/auth/logout.ts
  frontend/src/pages/api/private/me/index.ts
  frontend/src/pages/api/private/me/media.ts
Labels: type: feature

#4925 fix(frontend-config): use guest access level instead of allowAnonymous
  frontend/cypress/support/config.ts
  frontend/src/api/config/types.ts
  frontend/src/components/login-page/guest/guest-card.tsx
  frontend/src/pages/api/private/config.ts
Labels: type: bug

#4926 enhancement(login): add redirectBackTo parameter to login button
  frontend/cypress/e2e/signInButton.spec.ts
  frontend/src/components/landing-layout/navigation/sign-in-button.tsx
Labels: type: feature enhancement
