Repository hedgedoc/hedgedoc, pull requests merged in 2023-07, with the labels that each got.

#4365 Added documentation to enable production logging
  docs/content/dev/setup/frontend.md
Labels: type: documentation

#4373 fix(ci): remove possible command injection in netlify deployment
  .github/workflows/frontend-netlify-deploy-main.yml
Labels: type: ci/cd

#4419 fix(frontend): use correct translations for privacy and term of use links
  frontend/src/components/register-page/register-infos.tsx
Labels: ci: force deployment

#4437 fix: add new slogan
  public/views/index/body.ejs
  public/views/index/head.ejs
Labels: type: feature enhancement

#4436 fix: add new slogan
  LICENSE
  frontend/locales/en.json
Labels: type: feature enhancement

#4455 fix: don't create notes if not found in presentation route
  lib/web/note/controller.js
  lib/web/note/util.js
Labels: type: bug

#4345 feat(frontend): delete revision
  frontend/cypress/e2e/revision.spec.ts
  frontend/locales/en.json
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revision-sidebar-entry.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/delete-revision-modal.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-list.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal-body.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal-footer.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal.tsx
Labels: type: feature

#4539 fix(commons): replace microbundle with bash based compile script
  commons/.eslintrc.cjs
  commons/build.sh
  commons/jest.config.json
  commons/package.json
  commons/tsconfig.base.json
  commons/tsconfig.base.json.license
  commons/tsconfig.cjs.json
  commons/tsconfig.cjs.json.license
  commons/tsconfig.esm.json
  commons/tsconfig.esm.json.license
  commons/tsconfig.json.license
  commons/tsconfig.test.json
  commons/tsconfig.test.json.license
  frontend/src/components/editor-page/editor-pane/hooks/yjs/frontend-websocket-adapter.ts
  yarn.lock
Labels: type: bug
