Repository hedgedoc/hedgedoc, pull requests merged in 2024-09, with the labels that each got.

#5801 fix(packages): backend was missing uuid package
  backend/package.json
  yarn.lock
Labels: type: bug

#5810 Use correct dark-mode selector in css
  frontend/global-styles/github-markdown.scss
  frontend/global-styles/index.scss
  frontend/src/components/common/highlighted-code/highlighted-code.module.scss
  frontend/src/components/editor-page/sidebar/style/sidebar.module.scss
Labels: type: bug

#5807 Allow to keep uploads on note deletion
  backend/src/history/history-entry.dto.ts
  backend/src/history/history.service.ts
  frontend/locales/en.json
  frontend/src/api/history/types.ts
  frontend/src/api/notes/index.ts
  frontend/src/components/common/modals/deletion-modal.tsx
  frontend/src/components/editor-page/hooks/use-update-local-history-entry.ts
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/delete-note-sidebar-entry/delete-note-modal.tsx
  frontend/src/components/editor-page/sidebar/specific-sidebar-entries/delete-note-sidebar-entry/delete-note-sidebar-entry.tsx
  frontend/src/components/history-page/entry-menu/delete-note-item.tsx
  frontend/src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx
  frontend/src/components/history-page/entry-menu/entry-menu.tsx
  frontend/src/components/history-page/entry-menu/remove-note-entry-item.tsx
  frontend/src/components/history-page/history-card/history-card.tsx
  frontend/src/components/history-page/history-content/history-content.tsx
  frontend/src/components/history-page/history-table/history-table-row.tsx
  frontend/src/pages/api/private/me/history.ts
  frontend/src/redux/history/methods.ts
Labels: type: feature enhancement

#5805 Drop passport, rename PublicAuthToken to ApiToken
  backend/package.json
  backend/src/api-token/api-token.dto.ts
  backend/src/api-token/api-token.entity.ts
  backend/src/api-token/api-token.guard.ts
  backend/src/api-token/api-token.module.ts
  backend/src/api-token/api-token.service.spec.ts
  backend/src/api-token/api-token.service.ts
  backend/src/api-token/mock-api-token.guard.ts
  backend/src/api/private/private-api.module.ts
  backend/src/api/private/tokens/api-tokens.controller.ts
  backend/src/api/public/alias/alias.controller.ts
  backend/src/api/public/me/me.controller.ts
  backend/src/api/public/media/media.controller.ts
  backend/src/api/public/monitoring/monitoring.controller.ts
  backend/src/api/public/notes/notes.controller.ts
  backend/src/api/public/public-api.module.ts
  backend/src/app.module.ts
  backend/src/history/history.service.spec.ts
  backend/src/media/media.service.spec.ts
  backend/src/migrations/mariadb-1726271650566-init.ts
  backend/src/migrations/postgres-1726271794336-init.ts
  backend/src/migrations/sqlite-1726271503150-init.ts
  backend/src/notes/alias.service.spec.ts
  backend/src/notes/notes.service.spec.ts
  backend/src/permissions/permissions.service.spec.ts
  backend/src/public-auth-token/public-auth-token.module.ts
  backend/src/public-auth-token/public-auth-token.strategy.ts
  backend/src/realtime/websocket/websocket.gateway.spec.ts
  backend/src/revisions/revisions.service.spec.ts
  backend/src/seed.ts
  backend/src/users/user.entity.ts
  backend/test/test-setup.ts
  yarn.lock
Labels: feature: auth

#5349 feat(backend revision): add clean-up note revisions job
  backend/src/config/mock/note.config.mock.ts
  backend/src/config/note.config.spec.ts
  backend/src/config/note.config.ts
  backend/src/revisions/revisions.module.ts
  backend/src/revisions/revisions.service.spec.ts
  backend/src/revisions/revisions.service.ts
  docs/content/references/config/notes.md
Labels: type: feature
