Repository hedgedoc/hedgedoc, pull requests merged in 2024-01, with the labels that each got.

#5382 fix(ci): artifact-upload in e2e tests
  .github/workflows/e2e-tests.yml
Labels: type: ci/cd

#5352 chore: Update E2E test script name in docs
  docs/content/how-to/develop/frontend.md
Labels: type: documentation

#5400 deps: pin node types
  package.json
  yarn.lock
Labels: type: bug

#5384 refactor: Replace baseUrl with consumer/provider in width-based-table-of-contents
  frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
  frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
  frontend/src/components/render-page/renderers/document/width-based-table-of-contents.tsx
Labels: type: code quality enhancement

#5434 chore(deps): Downgrade turbo
  package.json
  yarn.lock
Labels: type: bug
