Repository hedgedoc/hedgedoc, pull requests merged in 2024-08, with the labels that each got.

#5598 fix(frontend): do not hardcode example.org, do not prebuild motd
  frontend/src/components/global-dialogs/motd-modal/fetch-motd.ts
  frontend/src/utils/base-url-from-env-extractor.ts
Labels: type: bug

#5599 enhancement(realtime): send metadata update on revision save
  backend/src/realtime/realtime-note/realtime-note.service.ts
  backend/src/realtime/realtime-note/realtime-note.spec.ts
  backend/src/realtime/realtime-note/realtime-note.ts
Labels: type: feature enhancement

#5601 Switch from bcrypt to argon2id
  backend/package.json
  backend/src/identity/identity.service.ts
  backend/src/utils/password.spec.ts
  backend/src/utils/password.ts
  yarn.lock
Labels: type: bug, security, feature: auth

#5603 [1.x] Fix screen readers announcing headings twice
  public/docs/release-notes.md
  public/js/extra.js
Labels: type: bug

#5602 Re-add editor mode buttons
  frontend/src/app/(editor)/@appBar/n/[noteId]/editor-app-bar.tsx
  frontend/src/app/(editor)/@appBar/n/[noteId]/editor-mode-extended-app-bar.tsx
  frontend/src/components/editor-page/splitter/__snapshots__/splitter.spec.tsx.snap
  frontend/src/components/editor-page/splitter/hooks/use-keyboard-shortcuts.ts
  frontend/src/components/editor-page/splitter/splitter.spec.tsx
  frontend/src/components/editor-page/splitter/splitter.tsx
  frontend/src/components/layout/app-bar/base-app-bar.tsx
  frontend/src/redux/editor-config/initial-state.ts
  frontend/src/redux/editor-config/methods.ts
  frontend/src/redux/editor-config/slice.ts
  frontend/src/redux/editor-config/types.ts
Labels: type: feature, scope: frontend, feature: editor

#5557 docs: add google cloud storage bucket guide
  docs/content/guides/s3-google-cloud-storage.md
  docs/mkdocs.yml
Labels: type: documentation
