Repository hedgedoc/hedgedoc, pull requests merged in 2025-02, with the labels that each got.

#5947 fix: set HSTS preload attribute to false by default
  docs/content/configuration.md
  lib/config/default.js
  public/docs/release-notes.md
Labels: type: bug

#5966 chore(translations): update languages from poeditor
  locales/_supported.json
  locales/nl-be.json
Labels: type: maintenance

#5994 docs(setup): list of supported docker architectures
  docs/content/setup/docker.md
Labels: type: documentation

#6000 fix(turborepo): passthrough HD_* env vars by config option
  package.json
  turbo.json
Labels: type: bug

#5974 docs: add release_checklist.md
  docs/content/dev/release_checklist.md
  docs/mkdocs.yml
Labels: type: documentation

#5999 fix(login): prevent default for new user confirmation form event
  frontend/src/components/login-page/new-user/new-user-card.tsx
Labels: type: bug, scope: frontend, feature: auth
